### ISSUE TITLE
Einkaufliste unter usern teilen

### ISSUE THREAD

**Issue by gu3nter** [SEPIA-Framework/sepia-docs#101]
Hallo,

ich habe folgendes Problem:
Ich würde gerne mit dem DIY client hin und wieder eine Einkaufliste erstellen, Jetzt habe ich das Problem, dass wenn ich mich mim Handy unter dem gleichen User einlogge, um die Einkaufsliste einzusehen, dann wird mein DIY client ausgeloggt und umgekehrt.

Kann man das Problem irgendwie umgeehen, evtl. mit mehreren Usern, aber können diesen dann auch die gleiche Liste einsehen?

Gruß

**Comment by fquirin** [comment]
Hi @gu3nter , da du das Issue geschlossen hast nehme ich an, dass sich das Problem erledigt hat?
Grundsätzlich solltest du jedem Client eine eigene ID geben, dann wirst du nicht ausgeloggt wenn du dich irgendwo anders mit dem selben Account anmeldest.
Mehrere User können eine Liste leider nur einmalig kopieren zur Zeit (Verknüpfung geht verloren), über das Share Feature habe ich aber schon mehrmals nachgedacht und bin sicher, dass sich da was tun wird im Laufe des Jahres :-)

**Comment by gu3nter** [comment]
OK danke für die Antwort, hatte das mit den IDS schon rausbekommen
