### ISSUE TITLE
Is Sepia ready for openHAB 3?

### ISSUE THREAD

**Issue by Smarthome-Creator** [SEPIA-Framework/sepia-docs#113]
Hello,
i upgraded my openHAB to the last version 3.
Since openHAB 3 only connections are allowed with api token to use it with external services.

I think S.E.P.I.A is ready for it but how are the settings in control hub?

To be exact the settings for "smarthome_hub_auth_type" and "smarthome_hub_auth_data"?
I think "smarthome_hub_auth_data" is for the api key?
But what is the setting for "auth_type"?

Thanks and regards

**Comment by fquirin** [comment]
Hi @Smarthome-Creator ,

I think I have to look into the docs to see how the API key is used in OpenHAB 3. It may require some smaller changes in the SEPIA code (that I could probably sneak-in before the next update ^^).

`auth_type` is currently available only for BASIC AUTH ("plain") which is probably not what Open HAB 3 uses :-/

**Comment by Smarthome-Creator** [comment]
At the moment OH3 uses basic_auth and Api key authentication.
What are the valuse in Core Settings for basic_auth?

![OH basic auth settings](https://user-images.githubusercontent.com/61153058/116439893-54e3d700-a850-11eb-95c0-63db697931ce.JPG)

smarthome_hub_user ?
smarthome_hub_passwd ?

**Comment by fquirin** [comment]
Here is a bit of info about it [Smart-Home-Controls - adding-new-interfaces](https://github.com/SEPIA-Framework/sepia-docs/wiki/Smart-Home-Controls#adding-new-interfaces).
It should be:
```
smarthome_hub_auth_type = Basic
smarthome_hub_auth_data = [Base64 encoding of 'username:password']
```
Example for data: encoding of the string `username:password` should result in: `dXNlcm5hbWU6cGFzc3dvcmQ=` (if you use literally "username" as name and "password" as password. In Javascript (or your browser console) you can try: `btoa("username:password")`.

**Comment by Smarthome-Creator** [comment]
Thanks, it works again.
