### ISSUE TITLE
Smarthome devices with custom_config + more questions

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#130]
Hey,

first of all, thanks for the great work. i installed the last update and got it running so far. also the mqtt binding with Home Assistant is working.

i can create a "tv device" to turn it on and off.  when i want for example switch to netflix an the tv i can create another tv device named netflix (dont like it to do it for all apps)  or create a teach-sentence with smart device: <tv>;;androidbox and value: {"type":"text_raw","value":"netflix"}

is it possible to create diffrent values for the tv-device with the "custom_config"? 

is the google api (still needs a creditcard for the api key) still requiered for the geolocation search or can we use a diffrent geo-api service?

/roy

**Comment by royrogermcfreely** [comment]
you got some infos for this?
just asking

it works meanwhile with a lot of devices (arround 50)

**Comment by fquirin** [comment]
Sorry, I've been focused on finishing the next update and haven't had time to play with the custom service yet, but it's still on the to-do list in the top 3 ^^.

I have finished Graphhopper integration though ^^, it will be included in the next release, currently testing the last features :-)

**Comment by royrogermcfreely** [comment]
nice :)

and dont worry about that too much ;)

**Comment by royrogermcfreely** [comment]
If you need someone to test stuff, feel free to ask

**Comment by fquirin** [comment]
Ty, I will :slightly_smiling_face: :+1:

**Comment by fquirin** [comment]
Here is something to test :grin: : [SEPIA-Home v2.6.1](https://github.com/SEPIA-Framework/sepia-installation-and-setup/releases).

I've implemented a new smart-home feature called "general values". It's not very elegant but the best I could do without breaking too much ^^. Coming back to your initial question you should now be able to say something like "Set TV to value Netflix" ("TV auf Wert Netflix"). If you use the Teach-UI you could remap "TV to <val1>" to "Set TV to value <val1>" via `Execute Command(s)`.

Let me know if that works for you ... or if it breaks something existing ^^ :see_no_evil: .

**Comment by royrogermcfreely** [comment]
the new feature is pretty nice.

it works for my tv to call netflix, disney, kodi etc...

than i tried do to the same with my vacuum robot as device.
i can set the state to "gang" but not to kitchen, living room, sleepingroom etc.

sepia tells me that it could not find a right device.

but i can set the device vacuum to netflix, kodi etc... :D

setting devices states to numbers is working as usual.

do you know why this happens?

i tried it with a punch of random words but could not find a red line where sepia accept the value as state and where not

ps: graphhopper is awesome :)

**Comment by royrogermcfreely** [comment]
ah thanks now i know :)

i gave the vacuum device a location ("küche")
now i got it working with the following teaching: 
when i say "sauge <var1> <var2>" -> execute command: "gerät staubsauger in der küche auf wert <var2>"

so sepia tells me when i want to clean the kitchen: "staubsauger in der Küche auf küche, wird gemacht." 
thats not a dealbreaker for me.

maybe i try your robocleaner demo someday.

thanks again for this feature. i reduced my smart home devices from over 40 to about 15 devices. was a lot of work, but now its much simpler to add new stuff to my smarthome :)

**Comment by fquirin** [comment]
> thanks again for this feature. i reduced my smart home devices from over 40 to about 15 devices. was a lot of work, but now its much simpler to add new stuff to my smarthome :)

niceee :-D

**Comment by fquirin** [comment]
> so sepia tells me when i want to clean the kitchen: "staubsauger in der Küche auf küche, wird gemacht."
thats not a dealbreaker for me.

Btw, you can actually customize the answer inside the teach command as well ;-)
