### ISSUE TITLE
Server start fails due to Elasticsearch not ready yet?

### ISSUE THREAD

**Issue by fquirin** [SEPIA-Framework/sepia-docs#131]
**Describe the bug**
When inside a Docker container the server startup fails with the assist-server complaining about account validation (core accounts). An additional wait after Elasticsearch start seems to fix this. It seems Elasticsearch isn't 100% ready yet.

**SEPIA client and server versions**
- SEPIA-Server version: SEPIA-Home v2.6.0

Solution: Maybe we can improve the wait script that checks if Elasticsearch is ready.

**Comment by BieJay93** [comment]
Okay, that's strange, because I also tested &timeout=3, without any errors..

I'm using Debian as host machine.
With an Intel i7 6700 and 48GB RAM, so performance shouldn't be the problem.

**Comment by fquirin** [comment]
> Okay, that's strange, because I also tested &timeout=3, without any errors..

if you've used exactly that `timeout=3` than it might have recognized the value as invalid and used the default (=30s). The value has to be given together with the unit `3000ms, 3s, 1m, 1h, ...` 

> With an Intel i7 6700 and 48GB RAM, so performance shouldn't be the problem.

that should indeed be pretty fast :rocket:

**Comment by BieJay93** [comment]
New day, new try. 
I wasn't really sure if i used it with the unit, so i tested again.
This time definitely with the unit. I tried `3s, 6s, 10s & 20s`. 
No timeouts and no big differences in the startup time. Best value was 10s, with a response time of 15s. Maybe coincidence.

I hope it helps you.

**Comment by fquirin** [comment]
Thanks for the info. Its really confusing and totally not what the health check promises :sweat_smile:, but at least it seams to start up reliably now right? I'll keep an eye on that and see how it behaves when I build the next test version.

**Comment by BieJay93** [comment]
Yes, server is always starting up with this check. I'm already using this in my main sepia container. 
Many thanks :)

**Comment by fquirin** [comment]
The cahnges are integrated into [SEPIA-Home v2.6.1](https://github.com/SEPIA-Framework/sepia-installation-and-setup/releases) :slightly_smiling_face: - New Docker containers are not there yet but the old ones can simply be updated.
