### ISSUE TITLE
How to change WakewordSensitivity in RPI DIY Client

### ISSUE THREAD

**Issue by gu3nter** [SEPIA-Framework/sepia-docs#132]
Hallo,

erstmal vielen Dank für die geilen neuen Features in der V2.6!
ich habe heute die neue Version 2.6 installiert und wollte nun das Wakeword "Jarvis" einrichten. Jetzt ist mir aufgefallen, dass ich in den clexi/www/sepia/setting.js keine Option hierfür finde.
Nun habe ich versucht diese selbst einzufügen, aber die wakeword Erkennung hat sich dabei leider nicht verbessert. ich hoffe ihr könnt mir weiter helfen., was genau in den Settings ergänzt werden sollte.

Mein Versuch:
                        "wakeWordNames": "Computer, Jarvis",
                        "wakeWordVersion": "1.9",
                        "wakeWordSensitivities": [0.9],

`SepiaFW.settings = {
        headless: {
                device: {
                        "host-name": "localhost",
                        "deviceId": "o1",
                        "deviceLocalSiteData": {
                                "location": "home",
                                "type": "room",
                                "name": "livingroom",
                                "index": ""
                        },
                        "mediaDevices": {
                                "mic": {},
                                "player": {},
                                "tts": {},
                                "fx": {}
                        },
                        "microphoneSettings": {
                                "gain": 1.0
                        },
                        "deviceSounds": {
                                "micConfirm": "sounds/coin.mp3",
                                "alarm": "sounds/alarm.mp3"
                        },
                        "wakeWordNames": "Computer, Jarvis",
                        "wakeWordVersion": "1.9",
                        "wakeWordSensitivities": [0.9],
                        "voiceEngine": "sepia",
                        "voiceCustomServerURI": "",
                        "en-voice": "",
                        "de-voice": "de-DE pico f",
                        "asrEngine": "native",
                        "asrServerURI": "http://localhost:20726/sepia/stt",
                        "asrServerUser": "any",
                        "asrServerToken": "test1234",
                        "en-asrModel": "",
                        "de-asrModel": ""
                },
`

Gruß

René

**Comment by fquirin** [comment]
Hi René,

Versuch mal das hier:
```
"wakeWordSensitivity": ["0.5"],
"wakeWordNames": "Jarvis",
"wakeWordVersion": "1.9",
```
Wenn es klappt kannst du noch mal testen ob das ww array erkannt wird: `["Computer", "Jarvis"]` (es kann sein dass das in die wakeWord.js muss).

Im client auf settings Seite 2 ist jetzt auch ein "Export" Knopf, der dir die Settings anzeigen sollte (falls du es vorher in den "Hey SEPIA" Settings definiert hast). Von dort kannst du es kopieren.

Am wichtigsten für das wake-word ist allerdings die Mikrofon Einstellung. In den Settings unter "Mediengeräte" kannst du jetzt dein Mikrofon testen. Ich muss da bei fast jedem Setup den input gain auf mindestens 10 erhöhen, damit es gut funktioniert.

Sag bescheid ob es geklappt hat ;-)

**Comment by gu3nter** [comment]
Super danke für die schnelle Antwort, werde das heute Abend testen und dir Feedback geben.

Wie kann ich denn in DIY headless mode auf Mediengeräte in den Settings gehen?
Könnte den Headless mode vorübergehen deaktivieren, jedoch weiß ich dann leider auch nicht wie ich auf Mediangeräte im DIY client komme. Kannst du mir hier helfen?

**Comment by fquirin** [comment]
Ja, das ist leider noch ein ungelöstes Problem, die Funktion kann bisher nur visuell bedient werden :see_no_evil:
Ich habe meistens einen Touchscreen angeschlossen, vielleicht hast du Monitor und Maus die man temporär anschließen könnte (und dann im 'pseudo-headless' modus starten)?
Welches Mikrofon benutzt du? Du könntest auf gut Glück auch einfach mal den gain auf 10 setzen (section "device") und gucken was passiert:
```
"microphoneSettings": {
    "gain": 10,
}
```

**Comment by gu3nter** [comment]
Bin noch nicht zum testen gekommen, jedoch schon einmal danke für die Antwort.
kann in den clexi settings das gain >1.0 gesetzt werden? Dachte 1.0 ist der Maximalwert?

Habe das ReSpeaker Mic Array, somit läuft es ja schon ganz gut, aber noch nicht perfekt :)

Mit dem pseudo headless teste ich dann später.
Wie muss ich das genau machen? Stelle auf pseudo headless um und besuche die http://localhost:20721/app/index.html um dort das gain herauszufinden? Blick da gerade nicht so durch :)

**Comment by gu3nter** [comment]
Hab's nun mit "wakeWordSensitivity": ["0.5"] probiert, jedoch noch ohne Erfolg.
Falls ich die richtige Syntax herausfinde werde ich sie hier posten.

Falls du mir noch mit den Mediengeräten im pseudo headless Mode helfen könntest, wäre das super, also wie ich da hin gelange :).

**Comment by fquirin** [comment]
> kann in den clexi settings das gain >1.0 gesetzt werden?

Leider nicht. Die ganzen Media-Devices Settings sind leider noch nicht wirklich CLEXI kompatibel. Das einzige was bisher über CLEXI geht ist eine Liste mit media-devices auszulesen. Ich versuche das mal Schritt für Schritt zu erweitern.

> Dachte 1.0 ist der Maximalwert?

Für die WW sensitivity sind die Werte 0-1 erlaubt. Für Mikrofon 'gain' ist theoretisch alles erlaubt, 0.01 - 100 z.B., bei mir ist es oft zwischen 5-20.

> Habe das ReSpeaker Mic Array, somit läuft es ja schon ganz gut, aber noch nicht perfekt :)

Das 2er oder das 4er? Das 4er ist mmn noch mal deutlich besser aber auch das 2er hatte ich erst kürzlich mir "Hey Edison" recht erfolgreich eingesetzt.

> Wie muss ich das genau machen? Stelle auf pseudo headless um und besuche die http://localhost:20721/app/index.html um dort das gain herauszufinden? Blick da gerade nicht so durch :)

"Pesudo-headless" heißt eigentlich nur, dass der Client sich weiterhin wie im "headless" Modus verhält, also z.B. automatisch ins Setup wechselt und die die settings.js lädt, dabei allerdings die grafische Ausgabe beibehält. Das ist quasi wie der Wechsel vom Amazon Echo Dot zum Echo Show ;-) (smart-speaker -> smart-display). Du könntest dann also eine Maus und Tastatur direkt an den Raspberry Pi anschließen und damit die Einstellungen in der UI prüfen.

> Hab's nun mit "wakeWordSensitivity": ["0.5"] probiert, jedoch noch ohne Erfolg.
Falls ich die richtige Syntax herausfinde werde ich sie hier posten.

Syntax sieht ok aus, vielleicht bewirkt es nur einfach nicht viel weil die Lautstärker zu niedrig ist :thinking: . Ich hab bei mir noch mal 0.1-0.9 getestet und 0.9 ist deutlich leichter auszulösen, allerdings ist auch 0.1 noch nicht super hart.

Versuch mal in der settings.js folgendes:
```
"wakeWordSensitivity": ["0.5"],
"wakeWordNames": "Jarvis",
"wakeWordVersion": "1.9",
"microphoneSettings": {
      "gain": 15,
  }
```

**Comment by gu3nter** [comment]
werde mich mit dem gain ein wenig speielen, voielen Dank für deine Tipps.

Eine frage hätte ich da noch:
Habe das ReSpeaker USB Mic Array (https://wiki.seeedstudio.com/ReSpeaker-USB-Mic-Array/) in deiner Anleitung gibt es eine config für asoundrc hättest du auch eine für das usb mic array?

PS: habe die 6_channels_firmware.bin des mics installiert

**Comment by fquirin** [comment]
Oh nice, das wollte ich mir auch mal besorgen, war aber irgendwie immer vergriffen wenn ich mal geguckt hatte. Heute hab ich mal wieder mit dem 4mic HAT rumgespielt ... und mich abermals davon überzeugt dass der definitiv mit die beste Qualität liefert :-) Tatsächlich hatte ich da sogar den gain auf 1.0 gelassen und den Rest über 'pulsemixer' geregelt.

> in deiner Anleitung gibt es eine config für asoundrc hättest du auch eine für das usb mic array?

Theoretisch müsste die [standard USB asoundrc](https://github.com/SEPIA-Framework/sepia-installation-and-setup/blob/master/sepia-client-installation/rpi/asoundrc_usb_mic) eigentlich auch funktionieren, allerdings weiß ich nicht ob sich das Gerät einfach wie ein normales USB verhält.

Du hast doch die neuste SEPIA DIY Client Version oder? Da musste ich nun nämlich wegen einem der letzten Raspberry Pi OS Updates und der neuen Media-Devices Einstellung in SEPIA doch auf Pulseaudio wechseln und dann brauchst du eventuell keine spezielle asoundrc :thinking: . Im nachhinein bin ich ganz zufrieden mit Pulseaudio (lange Zeit mein Alptraum ^^) weil der Pulsemixer und die Geräteauswahl ganz gut klappen. Versuch mal:  
- `sudo apt-get install -y --no-install-recommends pulsemixer`  
- Dann starten mit `pulsemixer` und mit TAB durch die Menüs navigieren (die F-Tasten crashen bei mir das Programm ^^).

Damit kannst du auch während der Client läuft die Lautstärken ändern :-)

**Comment by gu3nter** [comment]
HAbe bei der Sepia und DIY Client installation noch gar keine asoundrc installs durchgeführt. Funktioniert auch soweit ohne Probleme, dachte nur dass die asoundrc Einstellung noch etwas verbessert, aber dann ist das wohl nicht so ;)

geil, werde ich dann testen mit dem pulsemixer.

PS: Habe mir raspberry m,it der 64bit version installiert, alles läuft reibungslos, also SEPIA und der DIY Client.
mit deinen Anleitungen.
Beim installieren des DIY Clients, habe ich aber in der install_sepia_client.sh
Zeile 53 ff von 
wget http://ftp.de.debian.org/debian/pool/non-free/s/svox/<html>
<body>


libttspico0_1.0+git20130326-9_arm64.deb
--



</body>
</html>
wget http://ftp.de.debian.org/debian/pool/non-free/s/svox/libttspico-utils_1.0+git20130326-9_armhf.deb
# apt-get install -f ./libttspico0_1.0+git20130326-9_armhf.deb ./libttspico-utils_1.0+git20130326-9_armhf.deb
sudo dpkg -i libttspico0_1.0+git20130326-9_armhf.deb
sudo dpkg -i libttspico-utils_1.0+git20130326-9_armhf.deb

zu
wget http://ftp.de.debian.org/debian/pool/non-free/s/svox/libttspico0_1.0+git20130326-9_armhf.deb
wget http://ftp.de.debian.org/debian/pool/non-free/s/svox/libttspico-utils_1.0+git20130326-9_armhf.deb
# apt-get install -f ./libttspico0_1.0+git20130326-9_armhf.deb ./libttspico-utils_1.0+git20130326-9_armhf.deb
sudo dpkg -i libttspico0_1.0+git20130326-9_armhf.deb
sudo dpkg -i libttspico-utils_1.0+git20130326-9_armhf.deb

**Comment by fquirin** [comment]
> PS: Habe mir raspberry mit der 64bit version installiert, alles läuft reibungslos, also SEPIA und der DIY Client, mit deinen Anleitungen.
Beim installieren des DIY Clients, habe ich aber in der install_sepia_client.sh
Zeile 53 ff von ...

Zufällig hab ich das gleiche Problem Heute auch entdeckt und [einen Fix in den 'dev' branch committed](https://github.com/SEPIA-Framework/sepia-installation-and-setup/blob/dev/sepia-client-installation/rpi/install_sepia_client.sh#L53) :see_no_evil: 
Das gleiche Problem gabs auch im Server Setup, ich hatte nur vergessen es zu übertragen :-|
Aber cool dass du den Fix selbst auch gefunden hast :+1: 

> Kann mit dem raspberry os und sepia spotify abgespielt werden? Bekomme das mit der api nicht hin?

Mit der Frage schlage ich mich jetzt auch schon länger rum :-/. Kurz gesagt: Es gibt noch keine Lösung die wirklich gut funktioniert :-(.
Die längere Geschichte: Die Track Suche ist kein Problem, theoretisch könnte man auch Playlisten managen, aber alle embedding Möglichkeiten von Spotify spielen die Musik nur ab wenn der User selbst auf den Play Button drückt, deswegen kam das Spotify Widget nie aus dem Alpha Status heraus. Was man wahrscheinlich machen muss ist einen [libspotify](https://mopidy.github.io/libspotify-archive/) kompatiblen Player auf dem selben System zu hosten oder ein externes Gerät zu steuern. Libspotify ist dabei allerdings auch eine tragische Geschichte, denn Spotify hat es eigentlich abgeschafft, es bleibt aber die einzige Möglichkeit für web-apps einen Spotify player zu bauen :-(

Im SEPIA Client 0.24.0 lassen sich ja jetzt eigene media-player widgets bauen. Meine Hoffnung ist, dass man auf diese Weise noch eine Lösung findet :crossed_fingers:

**Comment by gu3nter** [comment]
Danke für den Hinweis mit pulssemixer, hat perfekt funktioniert.

Das heißt derzeit funktioniert Spotify nicht unter raspberry os in Verbindung mit SEPIA?

**Comment by fquirin** [comment]
> Das heißt derzeit funktioniert Spotify nicht unter raspberry os in Verbindung mit SEPIA?

Leider nur wenn man per touchscreen etc. selbst auf den "play" button drückt :disappointed: . Ich gebe die Hoffnung aber nicht auf ;-)

> YouTube habe ich leider derzeit noch nicht hin bekommen, bekomme immer Ben Api Fehler, hab aber ne Api eingetragen

Hast du den API key über den Control HUB eingetragen oder manuell in die '.properties' Datei? Den Server danach auch neu gestartet? ^^.
Was auch ohne API key ganz gut geht ist sich Playlists aus YouTube zu kopieren und über die Teach-UI einen Befehl zu erstellen, der die abspielt, z.B.: "Spiele meinen Rock Mix" etc. und dann kommt die YouTube Playlist.

**Comment by gu3nter** [comment]
Sorry habe leider noch zwei Fragen:

1. früher hat es im DIY Client unter den clexi Settings funktioniert, wenn ich unter 

            "Location": {
                "latitude": "XX.06203160881453",
                "longitude": "XX.19828992515203"
            }
meine GPS Daten eingegeben habe, dann konnte ich nach dem Wetter fragen. Jetzt kommt immer die Aussage:
Mir fehlen leider die Informationen zu deinem Standort.
Kannst du mir hier bitte weiter helfen?

Hatte in ne anderem Issue was von der neuen Export Funktion gelesen. somit habe ich im nbroswer meine GPS Daten eingegeben und mir in dem Js Export folgendes kopiert:


            "deviceGlobalLocation": {
                "latitude": "XX.06203160881453",
                "longitude": "XX.19828992515203"
            }
Jedoch hat das leider mein urspüngliches Problem nicht gelöst :(.

2. Welche genaue Maps API muss ich mir bei Google anlegen um z. B. Fragen zu können:
Wie ist das Wetter heute in Wien?

**Comment by fquirin** [comment]
> über control HUB hat es funktioniert, danke für den Hinweis. Komisch, dass es über die .properties nicht ging

Vielleicht war es die falsche .properties ? Die "custom" wäre die richtige (glaube ich :sweat_smile: , vergesse es selbst manchmal ^^).

> Sorry habe leider noch zwei Fragen

Dafür bin ich ja hier :-p

> Mir fehlen leider die Informationen zu deinem Standort. Kannst du mir hier bitte weiter helfen?

Deine Einstellung sieht eigentlich korrekt aus. Ich habe es gerade auch noch mal hiermit getestet:
```
"device": {
    ...
    "deviceGlobalLocation": {
        "latitude": "52.518620",
        "longitude": "13.376187"
    }
}
```

Mir ist allerdings eingefallen, dass du den Client einmal neu starten musst danach (einfacher reload über CLEXI reicht).
Die alte Einstellung müsste eigentlich auch noch gehen. Vorsicht allerdings! `"Location"` muss `"location"` sein (klein geschrieben)! JSON ist case-sensitive ;-)

> Welche genaue Maps API muss ich mir bei Google anlegen um z. B. Fragen zu können:
Wie ist das Wetter heute in Wien?

In einem anderen Issue wurde gerade diskutiert, dass Google jetzt eine Registrierung mit Kreditkarte benötigt für die Maps API :-(, deswegen versuche ich gerade Alternativen einzubauen (fertigzustellen). Grundsätzlich wäre es aber:
Directions API, Geocoding API, Places API

**Comment by gu3nter** [comment]
Super danke für die Antwort werde ich dann später testen.

Habe mir nun Youtube Premium zugelegt (Youtube Music ist da auch mit drinnen), meine Frage kann ich mit der Youtube API v3 auch Youtube Music streams abspielen lasse? 
So wie ich das sehe gibt es bei youtube musik mehr inhalte als in youtube selbst.

Meine zweite Frage:
wie kann ich eine playliste abspielen lassen? Habe es mit "spiele Playliste Meine Musik" probiert, jedoch wurde die Playliste nicht gefunden.

**Comment by fquirin** [comment]
> Ist es möglich sich beim DIY client mit seinem mit den Youtube Premium Daten einzuloggen, dass auch die Youtube Music Inhlate abgespielt werden können? Habe die Befürchtung dass das aktuell nicht funktioniert ;) :(:

Gute Frage. Bisher bin ich davon ausgegangen, dass das die gleiche API ist. Der SEPIA Server nutzt diese URL: `https://youtube.googleapis.com/youtube/v3/search`.
Können denn die Inhalte, die gefunden werden nicht abgespielt werden? Vielleicht muss man sich im Browser eigentlich erst anmelden bei Youtube Music? :thinking: .

> wie kann ich eine playliste abspielen lassen? Habe es mit "spiele Playliste Meine Musik" probiert, jedoch wurde die Playliste nicht gefunden.

Die NLU von SEPIA kann grundsätzlich unterscheiden zwischen "spiele Song ..." und "spiele Playlist ..." aber die YouTube API ist momentan noch hard-coded auf type=video (von: video, channel, playlist). Du kannst aber einfach Playlist URLs benutzen und über deinen eigenen Satz triggern (via Teach-UI).

> Edit: Habe nun die Wetter Location zum laufen bekommen

:+1:
