### ISSUE TITLE
publish mqtt to change smart device state not working

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#137]
Hello,

when i call sepia to turn on/off the light, i got a mqtt message like:

topic: sepia/smart-devices/light/gang
payload: {"state":"on"}

and my light goes on/off.

but when i publish with the same topic and payload the light goes on/off but the state of the device in sepia is not changing.

so sepia never knows the right state if i change the light state by myself. 

do i miss something?

/roy

**Comment by fquirin** [comment]
I quickly checked the code again and the MQTT class should track all incoming messages as well.
Where do you check the state? Inside the SEPIA control HUB or from the client via "what is the state of the lights in the livingroom?" etc..

**Comment by royrogermcfreely** [comment]
i checked the state both - inside the control hub and via "whats the state of..."

in node-red when i debug the mqtt i  get the right topics and payloads

**Comment by fquirin** [comment]
I'm a bit busy right now but I'll try to spin up my Node-RED again and double-check ...

**Comment by royrogermcfreely** [comment]
hey. 

i dont know what  the problem was but i deleted all my devices in the smart hub and created all new also the mqtt bridge.

and now its working.

so no worry, maybe i messed something up in my config or somewhere else.

**Comment by fquirin** [comment]
ok, thanks for the info and good to hear its working :relieved:
