### ISSUE TITLE
new allways on avatar for bedclock

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#140]
**Is your feature request related to a problem? Please describe.**
no, just another allways on avater 

**Describe the solution you'd like**
want a clock as allways on. so we can use it as a bedclock. and maybe the colour changes when you activate sepia

hope i descriped it right ;)

/roy

**Comment by fquirin** [comment]
I like the idea, will see what I can do :-). In the meantime ... have you seen the clock [custom HTML widget](https://github.com/SEPIA-Framework/sepia-docs/wiki/Creating-HTML-voice-widgets-for-the-SEPIA-client)? :grin: :

https://sepia-framework.github.io/app/index.html?view=%3Ccustom_data%3E/views/clock

**Comment by royrogermcfreely** [comment]
didnt see that. it looks nice.

will play arround with the background color so i can use it as at bedclock
