### ISSUE TITLE
backup smarthome devices and personal commands

### ISSUE THREAD

**Issue by royrogermcfreely** [SEPIA-Framework/sepia-docs#141]
how can i backup my smarthome devices/personal commands in sepia? so when i need to install a new sepia server i dont have to create everything new.

/roy

ps: what do you think about a thread where users can publish what they allready created with sepia - so other users get a hint what you can do

**Comment by fquirin** [comment]
> how can i backup my smarthome devices/personal commands in sepia? so when i need to install a new sepia server i dont have to create everything new.

You can use the backup script in your SEPIA home folder to create a backup of your whole server. It will create a ZIP that you can import again (with the import script). The update script is actually doing the same thing (backup - update - import).

If you want to explicitly export smart-home stuff I think it would be enough to make a snapshot of the Elasticsearch indices 'smart-interfaces' and 'smart-devices'. I'll try to document this in the near future ;-) 

> ps: what do you think about a thread where users can publish what they allready created with sepia - so other users get a hint what you can do

I'd love that :slightly_smiling_face: 
What do you think would be a good place to set this up? The [discussions](https://github.com/SEPIA-Framework/sepia-docs/discussions) section or something more popular? ^^

**Comment by royrogermcfreely** [comment]
``You can use the backup script in your SEPIA home folder to create a backup of your whole server. It will create a ZIP that you can import again (with the import script). The update script is actually doing the same thing (backup - update - import)``

thanks for the info. will try that.

`What do you think would be a good place to set this up? The discussions section or something more popular? ^^`
i think the discussion section will do it for the beginning - if it gets more popular, we can think about something else
