### ISSUE TITLE
Login failed! Sorry, but it seems the server does not answer :-(

### ISSUE THREAD

**Issue by Triple5soul89ny** [SEPIA-Framework/sepia-docs#15]
Hello Guys,

first of all thanks for your awsome work! 

I am pretty new in working with Linux, Raspbian and espacially sepia.
I want to try to setup an open source voice assistant to control my openhab items via voice command.

So I started to setup Raspbian, get the ReSpeaker 2-Mics Pi HAT running, and than used the quick guide to start setting up SEPIA. In my opinion all went through easy, so I configured Admin Password and connected to the tools Page.
After that, I set the connection to my openhab server.
After completed, I was able to see all my items on openhab an it was possible to switch my lights by klicking on the symbol.
Than I created an new user "openhab@sepia.local" and pushed it into the whitelist.

Now here  I have some problems. 
When I got to the http://sepia:20721/app/index.html Website and type my created user an password, I get this massage: Login failed! Sorry, but it seems the server does not answer :-(

Can anyone help me? What did I do wrong?

**Comment by sepia-assistant** [comment]
Hello :-)

Did you follow [these steps](https://github.com/SEPIA-Framework/sepia-docs/wiki/Create-and-Edit-Users) to create your new user? 
Especially the part: "...  then press 'put on whitelist' and you should see a success message. After that add the password for the user **and press 'create'**."

When you want to use the smart home service be sure to add the proper user roles as well [as described here](https://github.com/SEPIA-Framework/sepia-docs/wiki/Smart-Home-Controls#user-rights) ;-) (smarthomeguest and (optionally) smarthomeadmin).

Hope this helps, regards,
Florian

**Comment by Triple5soul89ny** [comment]
Hello Florian,

thanks for you answer. I have found the problem. I forgot to set the SEPIA host at APP Loginpage. Nö it works 😀👌

**Comment by sepia-assistant** [comment]
> Is it possible to make a kind of smartspeaker Out of the PI? For example say a Keywords an than a command, like "Alexa"?

Ah sorry, I just wanted to close this issue and noticed that you've had a question as well :sweat_smile: 
Yes it is possible! The scripts to transform your Pi into a smart speaker are currently in beta test phase, you can follow the progress here:
https://github.com/SEPIA-Framework/sepia-installation-and-setup/tree/dev/sepia-client-installation/rpi
In the meantime you can use your smart phone as "smart speaker" as well if you configure "hey SEPIA" in the settings and use the "always-on" mode (see tutorial). Obviously the same works in your desktop browser but you probably don't want to leave your PC switched on all the time ;-)
