### ISSUE TITLE
SmartHomeHub issue with FHEM

### ISSUE THREAD

**Issue by speedAmaster** [SEPIA-Framework/sepia-docs#16]
trying to "register sepia" leads to 

{
  "result": "fail",
  "error": "500 internal error",
  "info": "2020-02-16 23:56:05 WARNING - URLBuilder.java / getString() - Failed to build URL: [Ljava.lang.String;@b81fd8"
}

**Comment by speedAmaster** [comment]
PS: my FEHM server is https://192.168.178.99:8083/fhem
Sepia is on: http://192.168.178.91:20721//tools/index.html#!smart-home

**Comment by sepia-assistant** [comment]
Hello,

could you check the SEPIA Assist-Server log at `~/SEPIA/sepia-assist-server/log.out` please for a more detailed error description and double-check that your properties file at `~/SEPIA/sepia-assist-server/assist.custom.properties` contains exactly those 2 lines:
```
smarthome_hub_host=https://192.168.178.99:8083/fhem
smarthome_hub_name=fhem
```

It looks like your FHEM Url contains invalid characters or for some reason cannot be parsed.

**Comment by sepia-assistant** [comment]
I will close this issue assuming that you solved the problem? 
Feel free to comment here if you want to reopen it.
