### ISSUE TITLE
Raspberry Client Installation

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#162]
Am Ender der SEPIA Client Installation stehen folgende Zeilen:
`../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
   40 | #include <libudev.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [libusb.target.mk:154: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/pi/clexi/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Linux 5.10.92-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/clexi/node_modules/usb
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@2.1.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

Das ist bestimmt nicht so gedacht oder?
Ich habe `bash menu.sh dev` und `bash menu.sh` getestet. Beide Befehle verhalten sich gleich.
Hast Du eine Idee?

**Comment by fquirin** [comment]
Ich glaube das ist ein Problem mit der Node.js version. Ich musste die alte Node 10 Version stilllegen :-|.
Was sagt denn `node -v` und `npm -v` bei dir? 14 und 8 wären gut.

**Comment by gu3nter** [comment]
Hatte das Gleiche oder ein ähnliches Problem, weiß es nicht mehr genau.

Versuche Mal das hier, wenn ich mich nicht irre hat eines der beiden Packages zum Erfolg geführt:
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install libudev-dev

**Comment by fquirin** [comment]
In der Tat, wenn man Bluetooth skipped fehlt 'libudev-dev', das habe ich wohl vergessen einzutragen :-|.
'libusb-1.0-0-dev' habe ich nicht installiert, würde mich mal interessieren ob es auch ohne klappt bei dir @cap-blackbeard !

**Comment by cap-blackbeard** [comment]
> node -v

v14.19.0



> npm -v

6.14.16
