### ISSUE TITLE
SEPIA-Home Server docker Update

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#163]
Hallo,

ich versuche meinen laufenden SEPIA-Container mit `bash update-sepia.sh` auf Version 2.6.1 upzudaten.

Als Antwort erhalte ich:
```
Enter 'yes' to continue: yes

Ok. Good luck ;-)

Shutting down Assist-API
Shutting down Teach-API
Shutting down WebSocket Chat-API
Shutting down Elasticsearch
Shutting down Extensions: MaryTTS server

---- wait a second (or 3) ----

---- testing ----
``` 

Mir erscheint der Durchlauf sehr kurz. Und die Control-Hub-Info steht weiter auf 1.4.1 

Außerdem funktioniert nach der Neuinstallation meines Raspberry-Clients die Spracherkennung nicht und der Client gibt mir den Hinweis, dass ich auf eine neuere Serverversion updaten soll. Ich denke das hängt damit zusammen, dass ich das Update richtig ausführe?

**Comment by fquirin** [comment]
Mehr als das kommt gar nicht? Denn das ist nur der Anfang des Update scripts was the laufenden Server beendet :thinking:

**Comment by cap-blackbeard** [comment]
Nö. Mehr kommt nicht.
Habe den laufenden Container probiert.
Habe den Container beendet und den Setup-Container getestet.
Alles mit dem gleichen Ergebnis.

Gibt es nen log?

**Comment by fquirin** [comment]
Der Terminal Output ist eigentlich das log :grimacing: 
Nach `---- testing ----` wird das `sepia-status.sh` Skript ausgeführt was lediglich zwei 'ps' Befehle sind und dann müsste das Terminal `Starting backup ...` anzeigen (quasi der nächste Log Eintrag). Der einzige Error, der passieren kann wäre also in `sepia-status.sh` und müsste unmittelbar im Terminal auftauchen :thinking: 

Hängt das Terminal fest und muss abgebrochen werden oder springt es zurück in die Eingabe?
Kannst du mal `bash sepia-status.sh` alleine ausführen

**Comment by cap-blackbeard** [comment]
Es wird abgebrochen und springt zur Eingabe.

> bash sepia-status.sh
`admin        764     762  0 20:58 pts/2    00:00:00 grep java.*sepia-.*`

**Comment by fquirin** [comment]
und diese Zeile: `admin 764 762 0 20:58 pts/2 00:00:00 grep java.*sepia-.*` kommt beim update script nicht?

**Comment by cap-blackbeard** [comment]
Wenn ich jetzt `bash update-sepia.sh` eingebe, kommt:

```Enter 'yes' to continue: yes

Ok. Good luck ;-)

Shutting down Assist-API
Shutting down Teach-API
Shutting down WebSocket Chat-API
Shutting down Elasticsearch
./shutdown.sh: line 5: elasticPID.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Shutting down Extensions: MaryTTS server

---- wait a second (or 3) ----

---- testing ----

admin        768     755  0 21:00 pts/2    00:00:00 nano admin 764 762 0 20:58 pts/2 00:00:00 grep java.*sepia-.*
admin        803     801  0 21:02 pts/3    00:00:00 grep java.*sepia-.*
admin@406ec6cc15d1:~/SEPIA$ pi@Server01:~$

```

**Comment by fquirin** [comment]
und danach geht es wieder nicht weiter?
Also irgendwas verhält sich da extrem seltsam :grimacing: .

> `admin@406ec6cc15d1:~/SEPIA$ pi@Server01:~$`

Wenn ich mir diese Zeile angucke sieht es so aus als würde der Container komplett beendet und das Terminal springt raus ins Host System. Wie gehst du in den Container rein?
Falls du es nicht schon so machst versuch mal `sudo docker exec -it sepia_home /bin/bash` vom Host System.

**Comment by cap-blackbeard** [comment]
`sudo docker exec -it SEPIA_Home_Framework.1.wrh1xnmleyph8izsfg24gp88z /bin/bash`
```Enter 'yes' to continue: yes

Ok. Good luck ;-)

Shutting down Assist-API
Shutting down Teach-API
Shutting down WebSocket Chat-API
Shutting down Elasticsearch
./shutdown.sh: line 5: elasticPID.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Shutting down Extensions: MaryTTS server

---- wait a second (or 3) ----

---- testing ----

admin@ae637d253be6:~/SEPIA$```

**Comment by fquirin** [comment]
Ich frage mich ob das Terminal vielleicht einfach nur den Fehler verschluckt aus unerklärlichen Gründen :thinking: 
Versuch mal bitte folgendes:
- `sudo docker exec -it SEPIA_Home_Framework.1.wrh1xnmleyph8izsfg24gp88z /bin/bash`
- `cd ~`
- `wget https://sepia-framework.github.io/install/sepia-home-rpi-update.sh`
- `bash sepia-home-rpi-update.sh`
- Und dann den Anweisungen folgen

**Comment by cap-blackbeard** [comment]
```Ok. Good luck ;-)

Shutting down Assist-API
Shutting down Teach-API
Shutting down WebSocket Chat-API
Shutting down Elasticsearch
./shutdown.sh: line 5: elasticPID.pid: No such file or directory
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Shutting down Extensions: MaryTTS server

---- wait a second (or 3) ----

---- testing ----

admin@ae637d253be6:~$```

**Comment by fquirin** [comment]
Ich habs gerade noch mal auf meinem x86 64bit System ausprobiert und es lief ohne Probleme durch. Es muss irgendeine Besonderheit geben in deinem Setup, die dafür sorgt, dass der Prozess ohne Fehlermeldung einfach abbricht  :thinking: .
Was genau war noch mal das Host-System? Die Container werden alle von Portainer gemanagt richtig?

Kannst du ein Backup machen mit `bash backup-sepia.sh`? Ich baue mal einen Container mit der neuen Version, vielleicht kannst du dann dort wenigstens das Backup importieren.

**Comment by cap-blackbeard** [comment]
Backup kann ich erstellen. Der Backupordner hat eine Größe von 22,8MB.

Das Host-System ist ein HP ProLiant ML350 Gen6 Server auf dem ich Debian installiert habe.
Die Container werden von Portainer gemanagt.
Allerdings kämpfe ich noch mit der Netzwerkkonfiguration der Container. Da ist bestimmt nicht alles optimal.

**Comment by fquirin** [comment]
> Das Host-System ist ein HP ProLiant ML350 Gen6 Server auf dem ich Debian installiert habe

Ach das war sogar Debian, komisch, das ist auch mein Default Host System und genug Saft hat die Kiste wahrscheinlich auch. Mir gehen da langsam die Ideen aus :-|. Vielleicht ein Problem mit dem Filesystem, aber das Backup hat ja scheinbar geklappt.

Ich habe den Docker Container upgedated (`sepia/home:v2.6.1_amd64`). Das bringt wahrscheinlich keinen Unterscheid für das Update (alle wichtigen Daten sind ja im shared folder) aber wer weiß ^^. 
Ich würde jetzt einmal deinen kompletten shared folder (SEPIA) sichern, zusammen mit dem Backup irgendwo zwischenlagern und dann den Rest des update Skriptes manuell ausführen (ich hoffe das passt so, habe etwas improvisiert ^^):
- `cd $HOME/SEPIA`
- `mkdir -p update && cd update`
- `rm  SEPIA-Home.zip && wget https://github.com/SEPIA-Framework/sepia-installation-and-setup/releases/latest/download/SEPIA-Home.zip`
- `unzip SEPIA-Home.zip -d $HOME/SEPIA`
- `cd $HOME`
- `unzip -o "path/to/your/backup.zip" -d $HOME/SEPIA` (hier den Pfad anpassen!)
- `cd $HOME/SEPIA`
- `bash setup.sh` und direkt wieder exit (das setzt nur die execute Berechtigungen)
- `cat version`

Und dann mal testen was passiert ^^.

**Comment by fquirin** [comment]
> Ich habe SEPIA-Backup.zip von 06.02.2022 gefunden! Aber leider keine aktuelleren. Die befinden sich alle lokal auf dem Host im user-Ordner.

Ja, gute Frage, der Container darf doch gar nicht dahin schreiben, zumindest nicht im Normalfall O_o.

So lange du ein Backup deines shared folders hast ist aber alles ok. Das kannst du im Grunde einfach über den aktuellen Ordner drüberkopieren. Besser noch: erst die Daten im aktuellen Ordner löschen und dann die Daten aus dem Backup reinkopieren (so vermeidest du einen mix aus alten und neuen Libraries etc.).

**Comment by cap-blackbeard** [comment]
> Läuft irgendwo ein Skript was den status des Servers überwacht und irgendeine Aktion durchführt wenn der Server down ist?

Ja. Tatsächlich habe ich damals docker im swarm-Modus eingerichtet, da mir die Service-Funktion gefallen hat. Der Service sorgt dafür, dass der Container neu gestartet wird, sobald er down geht.

**Comment by fquirin** [comment]
Dann hätten wir also endlich die Lösung gefunden :grin: , diesen Service bitte deaktivieren fürs Update ^^.
Wie prüft der eigentlich ob der Server noch läuft?

**Comment by cap-blackbeard** [comment]
Jup. Das wars.



> Wie prüft der eigentlich ob der Server noch läuft?

Wie das genau läuft kann ich Dir nicht sagen. Aber man erstellt für jeden Container einen Service. In diesem Service wird dann das zu verwendende Image, Raplicas (docker swarm), Enviroments, Mounts, Networks, Published Ports und z.B. Restart condition definiert.

Ich hatte den swarm mode eingerichtet, da ich ursprünglich mit 2 Rpi3b+ arbeiten wollte. Habe aber schnell gemerkt, dass die 3er mit 1GB RAM zu klein sind. Da ich jetzt den HP-Rechner habe, werde ich mich damit beschäftigen, wie ich den swarm-mode wieder abschalten kann und werde meine Container wohl klassisch laufen lassen. Ich blick nämlich nicht durch, wie den Containern feste IPs zugewiesen werden können... Aber grundsätzlich ist der swarm-mode bzgl. hohe Verfügbarkeit ne coole Sache. Wenn mans braucht ;-)

Übrigens vielen Dank für Dein Engagement!
Finde ich absolut unüblich, dass sich jemand so reinhängt!

**Comment by fquirin** [comment]
Ich hätte gedacht, dass man irgendwie eine Bedingung definieren muss, die beurteilen kann, ob der Server tatsächlich läuft, sowas wie einen Ping-Request etc. :thinking: . Naja Hauptsache es klappt jetzt ^^.

> Übrigens vielen Dank für Dein Engagement!
Finde ich absolut unüblich, dass sich jemand so reinhängt!

Kein Thema, ich will ja schließlich, dass jeder der Lust auf SEPIA hat es auch ohne Probleme nutzen kann :smiley:

**Comment by cap-blackbeard** [comment]
Also der ioBroker-Container z.B. nutzt ja irgendwie eine healthcheck. Meinst Du so etwas?
Der Service sorgt hauptsächlich dafür, dass der Container auf anderen swarm-Knoten wieder gestartet werden, wenn der ursprüngliche swarm-Knoten down geht.

**Comment by fquirin** [comment]
Das Update Skript schließt ja nur den Server, der Container sollte eigentlich weiterlaufen, zumindest wenn er mit dem 'on-docker' Skript gestartet wurde. Deshalb habe ich mich nur gefragt woher weiß der Service, dass der SEPIA Server down ist obwohl der Container noch läuft :thinking: . Dazu müsste man eigentlich einen SEPIA enpoint auf Erreichbarkeit prüfen.
