### ISSUE TITLE
nach Update des SEPIA-Server & DIY-Client keine MaryTTS Ausgabe 

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#164]
Nach dem Update des SEPIA-Home-Servers und Neuinstallation des DIY-Clients kann der Client die "de-DE marrytts m" Stimme nicht mehr benutzen.
**Der Chat zeigt: UI: TTS Fehler - Ausgabe konnte nicht generiert werden.**
Es funktionieren noch "automatic" und de-DE pico f Stimme.

Vielleich kann ich noch erklären, dass der MarryTTS-Server beim Containerstart scheinbar erfolgreich gestartet wird:

```
INFO: This extension is recommended for systems with 2GB memory or more.
....MaryTTS server looks GOOD.
```

**Comment by fquirin** [comment]
In der Tat, konnte den Fehler reproduzieren :grimacing: 
Da ist ein Bug in der neuen Config Datei: `~/SEPIA/sepia-assist-server/Xtensions/TTS/settings.json`, die `LOCALE` Variable für die deutschen Stimmen muss `"de"` sein, nicht `"de_DE"` wie bei den englischen Stimmen :-/. KA wie ich das übersehen konnte beim Testen :-(.
Kannst du die Datei mal ersetzen durch diese hier:
[settings.zip](https://github.com/SEPIA-Framework/sepia-docs/files/8074167/settings.zip)

**Comment by cap-blackbeard** [comment]
Fehler behoben!
Läuft wieder.
Danke!

**Comment by fquirin** [comment]
Tip: Du kannst auch mal die neuen [MBROLA voices ausprobieren](https://github.com/SEPIA-Framework/sepia-assist-server/blob/master/Xtensions/TTS/espeak-ng-mbrola/README.md), die sind überraschend gut für ihren geringen Resourcenverbrauch ^^.

**Comment by cap-blackbeard** [comment]
> MBROLA voices ausprobieren

Männlich2 könnte ganz nett sein. Aber SEPIA spricht zu schnell. Kann man die TTS-Ausgabegeschwindigkeit reduzieren?

**Comment by fquirin** [comment]
ja, in der `~/SEPIA/sepia-assist-server/Xtensions/TTS/settings.json` gibt es den Parameter `"speed"`, da kannst du mal mit rumspielen :-).
Danach muss immer der Server neu gestartet werden.
