### ISSUE TITLE
Probleme nach Setup DuckDNS and Let's Encrypt certificate

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#167]
Ich erreiche meinen SEPIA-Server nicht mehr per "Server-IP:20726/sepia/assist/tools/index.html" lokal im Netzwerk.
Auch der Raspberry-Client bekommt keine Verbindung mehr zum Server.
Der docker-Container scheint aber normal zu starten.

Ich habe die Installation nach der Beschreibung "https://github.com/SEPIA-Framework/sepia-docs/wiki/SSL-for-your-Server" durchlaufen und dachte, ich könne nach der Installation wie gewohnt von meinem Netzwerk intern auf den Server zugreifen.

Den Port 20276 möchte ich eigentlich noch nicht im Router freigeben, da ich vorher nen anderen Router kaufen wollte.

Hilfe ;-)

**Comment by cap-blackbeard** [comment]
Das '...duckdns.org.conf' Certifikat habe ich erstmal komplett entfernt/ verschoben. Darum kümmere ich mich später ;-)

Ich habe jetzt die self-signed Option installiert.
http://IP:20727 funktioniert
https://IP:20726 klappt nicht - woran kann das liegen? https://IP:20726/sepia/assist/app/index.html ist nicht erreichbar.

**Comment by fquirin** [comment]
Ist die HTTPS Adresse gar nicht zu erreichen, auch nicht im Browser? Oder beschwert er sich wegen dem self-signed SSL Zertifikat?

Da das Zertifikat selbst gemacht ist muss man es noch importieren im jeweiligen Client. Im DIY Client gibt es dafür z.B. das Script [import_self_signed_SSL_cert.sh](https://github.com/SEPIA-Framework/sepia-installation-and-setup/blob/master/sepia-client-installation/rpi/import_self_signed_SSL_cert.sh). Theoretisch müsste dann sowas gehen:
`bash import_self_signed_SSL_cert.sh "IP:20726" sepia-home`
Eventuell muss man danach noch das System neu starten, sollte zwar eigentlich nicht der Fall sein, aber ich hatte hin und wieder das Problem, dass auch nach dem Import Chromium nicht zufrieden war.
Am Windows PC kann man das Zertifikat über den Browser selbst speichern und importieren, in Android gibt es auch Möglichkeiten, einfach mal Googeln. Das hat bisher immer gut geklappt bei mir.

**Comment by fquirin** [comment]
> Genau. Edge erreicht die Seite nicht.

Das ist Windows Edge am PC nehme ich an? Wenn die http Adresse auf port 20727 funktioniert sollte er mit https und port 20726 eigentlich zumindest den Fehler zeigen "abgelehnt wegen Zertifikat" (grob gesagt ^^) und dir einen "Erweitert" Button anbieten um den Fehler zu ignorieren.
Versuch vielleicht mal die URL ohne Pfad hinten also `https://[hostname].local:20726` oder `https://[IP]:20726`

> Für die Verbindung von draußen möchte ich vorher nen anderen Router kaufen

Ja das ist sicherlich ratsam. Man sollte schon genau darauf achten, dass man nicht aus versehen das Heimnetz nach außen öffnet :sweat_smile: . In den SEPIA Server Settings gibt es auch noch eine Sektion "protected accounts" wo man User IDs eintragen kann, das ist ratsam um zu verhindern/erschweren, dass Account Passwörter via brute-force Methode geknackt werden.

**Comment by cap-blackbeard** [comment]
An manchen Tagen schäme ich mich für mich selbst!
Man muss ja eigentlich nur Lesen.

Habe bei der Konfiguration jetzt zuerst **Punkt 5: Clean up and remove ALL old SEPIA configs from NGINX...** ausgeführt. Und dann erst mit **Punkt 4: Set up NGINX with self-signed SSL...** weiter gemacht.

Läuft jetzt!

**Comment by fquirin** [comment]
Diese ganze Proxy und SSL Geschichte ist ja etwas kompliziert, also da muss man sich für nix schämen ;-)
Hauptsache es klappt jetzt! :-)
