### ISSUE TITLE
Can I use Porcupine 2.1 models?

### ISSUE THREAD

**Issue by sippeangelo** [SEPIA-Framework/sepia-docs#171]
I would really love to make a custom wake word, but the Picovoice Console only lets me train models for Porcupine 2.1 and I can't find any way to make it generate for older versions... Will there be support for 2.1, or is there some way I can get a 2.0 model out of it?

I tried just using it by pretending it's a 2.0 one but it didn't seem to work. I'm also not sure how to convert it to the .js file SEPIA expects either. I found a `convert_binary_to_array.sh` script but that didn't do it.

**Comment by fquirin** [comment]
I was worried that this might happen, actually I was complaining about 2.0 and 2.1 compatibility few days ago in the Porcupine issues section :-/. 

Unfortunately there is no way to "upgrade" old wake-word files. The next client version will have v2.1 support ... unless they release v2.2 before ;-)

**Comment by sippeangelo** [comment]
Nice! I'll try again next version then 👀

**Comment by fquirin** [comment]
Forgot to mention it here but the last update added v2.1 support :-)
