### ISSUE TITLE
DIY-Client mit Touchscreen

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#173]
Kannst Du eine virtuelle Tastatur empfehlen?
Der DIY-Client läuft mit Chromium?
https://chrome.google.com/webstore/detail/virtual-keyboard/pflmllfnnabikmfkkaddkoolinlfninn?hl=de würde die funktionieren?

**Comment by fquirin** [comment]
Die Extension könnte vermutlich funktionieren.

Ich habe überlegt vielleicht eine generelle Javascript Lösung anzubieten, z.B. das hier: https://furcan.github.io/KioskBoard/

Die Alternative (und eventuell bessere Variante) wäre eine Linux Lösung, die könnte man dann auch nutzen zum Login beim boot, z.B.: http://florence.sourceforge.net/english.html
Ich hatte das vor Ewigkeiten mal ausprobiert, sogar mit custom Design, aber dann irgendwie nicht weiter verfolgt :thinking:

**Comment by cap-blackbeard** [comment]
Habe es aktuell noch nicht getestet. Aber ich meine mich zu erinnern, dass sich "Florence" früher nicht automatisch öffnete, wenn ich ein Eingabefeld antippte? Ich glaube, ich musste die Tastatur bei X11 immer aus dem Menü starten.
Werde die Tage n Backup vom DIY-Client machen und mal ausprobieren, wie weit ich mit "Florence" komme. Denn wenn eine virtuelle Tastatur installiert ist, dann auch schon beim Login.

**Comment by fquirin** [comment]
> ich meine mich zu erinnern, dass sich "Florence" früher nicht automatisch öffnete, wenn ich ein Eingabefeld antippte

Irgendwie sowas habe ich auch in Erinnerung, wobei es eigentlich als Feature angegeben ist.

Ich habe mal 'simple-keyboard' als reine JS Lösung eingebaut. Die nächste Client Version wird es als "experimentelles" Feature beinhalten. Es ist noch etwas buggy aber im Grunde nicht schlecht :-).
