### ISSUE TITLE
 sepia-html-client-app: Voice Command Widget

### ISSUE THREAD

**Issue by SHU-red** [SEPIA-Framework/sepia-docs#178]
**Is your feature request related to a problem? Please describe.**
If you want to quickly access the sepia voice-command and its not possible to always "block" the microphone for hotword detection etc. 

**Describe the solution you'd like**
It could be nice to have a shortcut on the homescreen to directly open sepia app and trigger a voice command?!
(I think other apps (Google, Tasker, ...) also have this possibility)

**Describe alternatives you've considered**
- Hotword detection (already implemented)
- Gestures? In my case i am Using Nova-Launcher, which gives the possibility to triger certain functions --> These is something calles "Activities" i think? Dont know if Sepia App could provide some sort of interface to trigger direct voice command activation

**Additional context**
Nope

**Comment by fquirin** [comment]
You can actually define SEPIA as default assistant app and use the home button long-press feature to trigger the microphone :-)
If you want to keep GA as default and have the option to send custom intents via Nova launcher then this should be `android.intent.action.ASSIST` or `android.intent.action.VOICE_COMMAND`. What kind of options are there for "activities"?

**Comment by SHU-red** [comment]
Nice I tried it out!
One disadvantage is, that it does not work to use sepia if I'm not connected to my home network.

At the Activities section of Nova launcher I can just go to Links > Activities > S.E.P.I.A.
And choose ".Main activity"

I dont know what this exactly is
If I choose it and execute the gesture, the sepia app opens

**Comment by fquirin** [comment]
`Main activity` is usually simply the start page of an App so yes, this will only open it.
Maybe you can use apps like Automate or Tasker to create something like a homescreen direkt "action.

Unfortunately making a widget is not trivial. I once had some plans to do it but never really had the time to find out what is required and how much effort it is (it seemed more than I hoped).

**Comment by SHU-red** [comment]
No problem
Also for me it's just a "nice to have" feature 😉

**Comment by SHU-red** [comment]
Done for me
