### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by tlrider99** [SEPIA-Framework/sepia-docs#181]
Hi Florian,

I hope you are doin well.
The sd-card of my sepia server crashed so I had to install a new one and tried 2.6.1 on a new raspian. I run point 1-4 and 6 from your  sepia-home-rpi.sh script without errors
But point 1 of the setup script run in this error.

 ERROR - deleteAny - ElasticSearch - error in '_all': {"code":-1,"error":"java.net.ConnectException: Connection refused (Connection refused)","HTTP_REST_SUCCESS":false}

Thanks in advance
Dirk

**Comment by tlrider99** [comment]
user-interface error, sorry

**Comment by fquirin** [comment]
> The sd-card of my sepia server crashed so I had to install a new one

Ah crap :-( Did you make a backup from time to time? :sweat_smile: 
Maybe I should remind people to run the backup script once a month or so :see_no_evil:
