### ISSUE TITLE
Update von 2.6.1 auf 2.6.2

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#205]
Hallo Florian,

ich brauch mal wieder Hilfe!
Ich finde keine hilfreichen Infos, was ich machen muss.

Aktuell läuft der Docker Container mit dem Image 2.6.1_amd64.
Den Sepia-Ordner habe ich zur Sicherheit schon mal gesichert.
Kannst Du mir kurz die Schritte aufschreiben?
Oder den Link, falls es eine Anleitung gibt?

Grüße
Christian

**Comment by fquirin** [comment]
Hi Christian,

ich musste selbst wieder suchen =), aber ich wusste irgendwo hatte ich was dazu geschrieben ^^. Hilft das:

https://github.com/SEPIA-Framework/sepia-docs/wiki/SEPIA-inside-virtual-environments#update-your-container

**Comment by cap-blackbeard** [comment]
Hi,
ja, hat geholfen. Docker-Server läuft und der DiY-Client eigentlich auch. Aber...

- der Client hat früher per SEPIA-Stream die MaryTTS Stimmen ausgegeben. Diese sind jetzt nach dem Update nicht mehr aufgelistet. Musste ich die irgendwie aktivieren/ installieren?
- die Porcupine-Aktivierung bei Version 2.1_en schlägt fehl mit der Meldung: "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"
- unabhängig von Porcopine-Fehlermeldung. Ich hatte den Key früher in der settings.js eingetragen. Dieser wird jetzt ignoriert? Hat sich da seit dem Update was geändert oder habe ich ggf. nen (Schreib-)Fehler?

**Comment by cap-blackbeard** [comment]
> * der Client hat früher per SEPIA-Stream die MaryTTS Stimmen ausgegeben. Diese sind jetzt nach dem Update nicht mehr aufgelistet. Musste ich die irgendwie aktivieren/ installieren?

habs gefunden 😄 
https://github.com/SEPIA-Framework/sepia-assist-server/blob/master/Xtensions/TTS/marytts/INSTALL.md
läuft wieder 👍 

Die zwei Probleme beschäftigen mich aber nach wie vor:
> * die Porcupine-Aktivierung bei Version 2.1_en schlägt fehl mit der Meldung: "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"
> * unabhängig von Porcopine-Fehlermeldung. Ich hatte den Key früher in der settings.js eingetragen. Dieser wird jetzt ignoriert? Hat sich da seit dem Update was geändert oder habe ich ggf. nen (Schreib-)Fehler?

**Comment by fquirin** [comment]
Hi @cap-blackbeard ,

> die Porcupine-Aktivierung bei Version 2.1_en schlägt fehl mit der Meldung: "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"

Ich habe es gerade noch mal mit dem aktuellen release Client getestet (0.24.2) und es läuft ohne Fehler durch bei mir. Hier ist die Konfiguration:
```
{
    "headless": {
        "device": {
            ...
            "wakeWordAccessKeyPorcupine": "EhndhSN1g...",
            "wakeWordNames": "Computer",
            "wakeWordVersion": "2.1_en",
            "wakeWordRemoteUrl": "<sepia_website>/files/porcupine/"
        },
...
```

Als "wakeWordRemoteUrl" habe ich mal den public server genommen (die SEPIA GitHub Seite), weil ich gerade keinen 2.6.2 Server online hatte (alles im 2.7.0 Test-Mode gerade ^^). Der default `<assist_server>/files/wake-words/porcupine/` müsste aber auch gehen wenn du eingeloggt bist.

> Hat sich da seit dem Update was geändert oder habe ich ggf. nen (Schreib-)Fehler?

Eigentlich nicht.

**Comment by cap-blackbeard** [comment]
Hmm... gibt es eine Konstellation, dass der DIY-Client seine Einstellungen nicht in der settings.js speichert? Bzw. nicht die settings.js benutzt?
Ich habe am Client die Einstellungen für das WakeWord wieder auf Standard "Hey Sepia" gestellt (per Display, Maus und Tastatur)
Wenn ich per ssh die settings.js anschaue, dann ist da trotz Neustart "Jarvis", "2.1_en" und der Key eingetragen.

**Comment by fquirin** [comment]
> gibt es eine Konstellation, dass der DIY-Client seine Einstellungen nicht in der settings.js speichert?

Tatsächlich speichert der Client seine Einstellungen immer NUR im localstorage, sprich im Cache. Die `settings.js` wurde damals eingeführt, um den Client konfigurieren zu können, wenn kein Display existiert und ist "read-only". Sie wird auch nur benutzt wenn der Client im "headless" oder "pseudo-headless" (verhält sich wie headless aber mit Display) Modus ist.
In Zukunft würde ich gerne ein Interface schreiben, mit dem man die settings.js auch schreiben kann, aber momentan ist die "komfortabelste" Methode die Einstellungen über die `Client -> Einstellungen -> Account -> Device & App Settings: Exportieren` zu speichern und dann in die settings.js zu schreiben.

**Comment by cap-blackbeard** [comment]
Und sie settings.js wird immer beim Neustart gelesen?
Und dann müsste z.B. bei den wakeword-settings WakeWord aus der settings.js und der Key ... auftauchen?

Mein Client ist als pseudo-headless konfiguriert.

**Comment by fquirin** [comment]
Pseudo-headless konfiguriert den Client Start eigentlich mit einem der "headless" Parameter ([siehe URL Parameter](https://github.com/SEPIA-Framework/sepia-html-client-app#url-parameters)). Wenn der gesetzt ist müsste die `settings.js` bei jedem Start oder reload gelesen werden.

**Comment by cap-blackbeard** [comment]
Du meinst so: "http://serverIP:20726/sepia/assist/app/index.html?isHeadless" ??? Keine Ahnung, wie ich das vor dem Update gemacht hatte. Aber mit URL Parametern habe ich noch nie gearbeitet. Ist Neuland für mich.

**Comment by cap-blackbeard** [comment]
Hallo Florian,
kein Stress! Leider habe ich noch keine Lösung gefunden. Das eigentliche Problem ist, dass ich das ww JARVIS 2.1_en nicht mehr aktiviert bekomme. Folgende Meldung erscheint:

- "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"

Ich habe meinen Key über die neue Touchtastatur eingegeben. Dann war mein Versuch den Key und die ww-Aktivierung mit der settings.js zu übergeben. Klappt leider auch nicht. Ich vermute, dass meine settings.js überhaupt nicht geladen wird. Denn nichts von dem, was ich dort eintrage, wird geladen (weder ww noch skin noch Koordinaten...).
Übrigens, wenn ich den Key auf meinem Laptop benutze, dann wird dieser akzeptiert.

**Comment by fquirin** [comment]
>  Ich vermute, dass meine settings.js überhaupt nicht geladen wird. Denn nichts von dem, was ich dort eintrage, wird geladen (weder ww noch skin noch Koordinaten...).

Den Client startest du über die standard Methode, sprich auto-login beim boot des OS (über den Eintrag in der ~/.bashrc)?
Hast du die `~/sepia-client/run.sh` irgendwie modifiziert? Wenn nicht check mal was im Setup als modus angezeigt wird (~/sepia-client/setup.sh). Wenn da `headless` oder `pseudo-headless` steht, sollte der Client mit dem richtigen Befehl hochladen und dann auch die settings.js laden.
Wenn das trotzdem nicht funktioniert würde ich eventuell mal die [uninstall](https://github.com/SEPIA-Framework/sepia-installation-and-setup/tree/master/sepia-client-installation/rpi#basic-uninstallation-steps) Schritte versuchen und den Client dann neu installieren :-|.

**Comment by cap-blackbeard** [comment]
Ja. Der Client startet per auto-login.
Neu am Verhalten ist jetzt, dass der Debug Log ausgibt: Initialization took too long! ...
Das könnte tatsächlich sein. Mein Server (gesamt 8GB RAM) hat aktuell nur noch 500MB RAM frei.
Kann ich das timeout für den ww-start verlängern?

**Comment by cap-blackbeard** [comment]
Nö doch nicht. Habe eben noch nen anderen Container gestoppt und erhalte sofort wieder im Client die Meldung: "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"...

**Comment by fquirin** [comment]
500MB ist etwas knapp für den Client, wobei das 2.1 WW am wenigsten RAM benötigt (1.9 ist glaube ich am schlimmsten, weil Picovoice das hard-coded hat und damals viel zu großzügig war :-|).

> Initialization took too long! ...

wo genau kommt der Fehler noch mal? Ich kenne den, aber kann mich gerade nicht mehr erinnern ^^

**Comment by cap-blackbeard** [comment]
> Initialization took too long! ...

hat der Debug Log im Client ausgegeben, kurz nachdem ich im Client in den WakeWord-Settings auf den Start-Button gedrückt habe.

Aber nachdem ich einen weiteren docker-Container gestoppt habe hat der Server ca. 1,2GB verfügbar. Jetzt schreibt der Client wieder:
```
Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT
Error during setup of module: porcupine-wake-word-worker
ERROR: Failed to create module. -Name: Error - Message: 'pv_porcupine_init' failed with status INVALID_ARGUMENT
```

**Comment by fquirin** [comment]
> hat der Debug Log im Client ausgegeben, kurz nachdem ich im Client in den WakeWord-Settings auf den Start-Button gedrückt habe.

Ach ja, jetzt erinnere ich mich, das kommt vom recorder, wenn der zu lange braucht, um zu starten. Das kann auch kommen, wenn der Client nach mic permission fragt und der User zu langsam klickt 😅 , aber ich denke hier war es doch der RAM der dann ausging.

> Jetzt schreibt der Client wieder: ..

Wenn du in den "Hey SEPIA" Settings guckst, ist da der API Key für PP v2.1 sichtbar? (expert settings)

**Comment by cap-blackbeard** [comment]
> Wenn du in den "Hey SEPIA" Settings guckst, ist da der API Key für PP v2.1 sichtbar? (expert settings)
Jupp ist sichtbar. Den habe ich ja per Hand eingetippt.

**Comment by fquirin** [comment]
> Ich habe eben nochmal das letzte Zeichen des Keys gelöscht und erhalte bei der ww-Aktivierung jetzt die Meldung: ...Invalid AccessKey

Ok, das heißt ja zumindest, dass der Key tatsächlich geladen wird und auch überprüft 🤔
Und der gleiche Key funktioniert am Desktop PC bzw. in der App hattest du gesagt, richtig?
Komisch irgendwie klingt das, als ob die Porcupine Dateien falsch oder kaputt sind.

**Comment by cap-blackbeard** [comment]
> Und der gleiche Key funktioniert am Desktop PC bzw. in der App hattest du gesagt, richtig?

Da war ich wohl zu voreilig stelle ich gerade fest. 
Der DebugLog schreibt:
`CREATING Wake-Word listener...
CREATING Wake-Word listener...`

Läuft also doch mit am PC und auch nicht am iPhone.

**Comment by fquirin** [comment]
> CREATING Wake-Word listener... CREATING Wake-Word listener...

Ohne richtige Fehlermeldung danach? Komisch, irgendwie ist das alles total inkonsistent 😖 .
Kannst du am PC mal F12 drücken für die Dev Tools und in der "Console" gucken ob da noch mehr Fehler stehen?

**Comment by cap-blackbeard** [comment]
> Die anderen Wake-Words gehen aber? v1.4 z.B.?

Das iPhone hat 1.9 Jarvis geladen.

Der Laptop mit Browser: Edge hält Sepia für nicht sicher.

**Comment by fquirin** [comment]
> Der Laptop mit Browser: Edge hält Sepia für nicht sicher.

Beim aktivieren des Mikrofons? Oder schon vorher? SSL hattest du noch nicht zum Laufen bekommen oder?
Die quick-n-dirty Methode müsste auch im Edge klappen: [Secure Origin Ausnahmen](https://github.com/SEPIA-Framework/sepia-docs/wiki/Set-up-web-browser-to-treat-your-local-IP-as-secure-origin)

**Comment by cap-blackbeard** [comment]
Ich dachte SSL mit dem Nginx Proxy Manager am Laufen zu haben. Aber Irgendwie ist da auch noch der Wurm drin. Mit dem iPhone kann ich Sepia von extern öffnen. Der Laptop zeigt nur die "Welcome to nginx!" Seite. ...



> [Secure Origin Ausnahmen](https://github.com/SEPIA-Framework/sepia-docs/wiki/Set-up-web-browser-to-treat-your-local-IP-as-secure-origin)

Jetzt steht im Sepia DebugLog zumindest nicht mehr, dass der Browser denkt, dass die Seite unsicher sei. 
`ENGINE URL: xtensions/picovoice/pv_porcupine.wasm
CREATED SEPIA Web Audio Picovoice module
inputSampleRate: 16000
inputSampleSize: 512
UPDATED Engine
CREATING Wake-Word listener...`
Aber über das CREATING Wake-Word listener... hinaus tut sich nichts.

**Comment by fquirin** [comment]
> Ich dachte SSL mit dem Nginx Proxy Manager am Laufen zu haben. Aber Irgendwie ist da auch noch der Wurm drin. Mit dem iPhone kann ich Sepia von extern öffnen. Der Laptop zeigt nur die "Welcome to nginx!" Seite. ...

War das über SEPIA selbst eingerichtet (Duck-DNS oder self-signed) oder über ein anderes Gerät im Netzwerk (NAS etc.)?

> Der Laptop hat Hey Sepia 1.4 geladen!
Und der Laptop lädt jetzt auch Jarvis 2.1_en !!!

Ok, also grundsätzlich geht es, das ist schon mal gut zu wissen 😅

**Comment by cap-blackbeard** [comment]
> War das über SEPIA selbst eingerichtet (Duck-DNS oder self-signed) oder über ein anderes Gerät im Netzwerk (NAS etc.)?

Ich hatte schon viel probiert/ gespielt. Aber jetzt müsste Sepia in der Standardkonfiguration sein. Ich habe den NginxProxyManager mit duck.dns Konfiguration als docker Container laufen und habe dort die Server-IP:20726 hinterlegt. Dem iPhone genügt das auch. Der Laptop hat da eben noch etwas gezickt.



> Ok, also grundsätzlich geht es, das ist schon mal gut zu wissen 😅

Jupp. Ging ja eben auch bis zum Update. Und was machen wir mit dem DiY-Client jetzt?

**Comment by fquirin** [comment]
> Und was machen wir mit dem DiY-Client jetzt?

Tja, gute Frage. Geht denn der Rest eigentlich vernünftig, wenn das wake-word deaktiviert ist? Insbesondere die Spracherkennung?
Ich würde im Zweifel vielleicht wirklich mal die "Uninstall" Schritte (siehe Link oben) ausführen oder noch mal komplett sauber anfangen.

**Comment by cap-blackbeard** [comment]
Ja. Der Rest funktioniert tatsächlich gut.
Aber egal. Einmal neu machen wird nicht schaden.

**Comment by fquirin** [comment]
Ok, wenn der gleiche Fehler wiederkommt, können wir das issue hier ja wieder auf machen.

**Comment by cap-blackbeard** [comment]
Der Client läuft wieder. Aber das ww bekomme ich trotzdem noch nicht zum Laufen.
Ich bekomme immer noch folgende Meldung:
> * "Porcupine error: Failed to create module. - Name Error - Message: 'pv_porcupine-init' failed with same status INVALID_ARGUMENT"

**Comment by fquirin** [comment]
Ist das jetzt der v0.25.0 Client? "headless" und nur die settings.js angepasst um das Jarvis v2.1 WW zu laden? Funktioniert das 1.4er Hey SEPIA WW?

**Comment by cap-blackbeard** [comment]
Genau. v0.25.0; pseudoheadless und die settings.js wird jetzt auch geladen. 

> 1.4er Hey SEPIA

ja. Funktioniert.

**Comment by fquirin** [comment]
kannst du mal die settings.js posten, also die relevanten Einträge. Die müssten ungefähr so aussehen:
```
{
    "headless": {
        "device": {
            "host-name": "my-sepia.domain",
			...
            "wakeWordNames": "Jarvis",
            "wakeWordVersion": "2.1_en",
            "wakeWordAccessKeyPorcupine": "...HABKMi/A==",
            "wakeWordRemoteUrl": "<assist_server>/files/wake-words/porcupine/"
        },
        "user": {
            ...
            "autoloadWakeWord": true,
            "useWakeWord": true
        },
        ...
    }
}
```

**Comment by cap-blackbeard** [comment]
`                       "wakeWordNames": "Jarvis",
                        "wakeWordVersion": "2.1_en",
                        "wakeWordAccessKeyPorcupine": "...M75oRlYRJtIxEg==",`

> "wakeWordRemoteUrl": "<assist_server>/files/wake-words/porcupine/"

Diesen Eintrag habe ich nicht.

**Comment by fquirin** [comment]
> Diesen Eintrag habe ich nicht.

Der ist normalerweise auch nicht nötig und hat den angegeben Wert als Default. Man kann theoretisch die URL zu den Dateien ändern, die nicht standardmäßig im Client enthalten sind. Beim Default wird es vom eigenen SEPIA Server geladen.

[EDIT] Um z.B. aus dem Git zu laden kann man folgendes nutzen: `<sepia_website>/files/porcupine/`

**Comment by cap-blackbeard** [comment]
Jetzt wo der Server v2.7.0 läuft, startet auch der Browser-Client am iPhone den Wake-Word listener nicht mehr.
```
STARTING Wake-Word listener...
STARTING Wake-Word listener...
```

Der DIY-Client schreibt jetzt:

```
ENGINE URL: http://server-IP:20726/sepia/assist/files/wake-words/porcupine/2.1_en/pv_porcupine.wasm
CREATED SEPIA Web Audio Picovoice module
inputSampleRate: 16000
inputSampleSize: 512
UPDATED Engine
CREATING Wake-Word-listener...
Error in module:porcupine-wake-word-worker - Failed to create module. - Name: Error - Message: 'pv_porcupine_init' failed with status INVALID_ARGUMENT
Error during setup of module: porcupine-wake-word-worker
ERROR: Failed to create module. - Name: Error - Message: 'pv_porcupine_init' failed with status INVALID_ARGUMENT
STARTING Wake-Word listener...
```

**Comment by fquirin** [comment]
Verflixt noch mal 😬.
Betrifft das jetzt "nur" DIY und iPhone oder auch den Desktop Browser?
Ich kann den Fehler leider nicht reproduzieren und die Fehlermeldung sagt ja auch nicht viel was einem hilft :-|. Meine beste Vermutung ist, dass irgendwas nicht richtig geladen wird und deshalb eine Funktion mit null aufgerufen wird, was dann zu `INVALID_ARGUMENT` führt. Aber das ist total ins Blaue geraten :-|

Dieser Pfad klappt ja schon mal: `http://server-IP:20726/sepia/assist/files/wake-words/porcupine/2.1_en/pv_porcupine.wasm`.
Vielleicht ist das Problem beim Laden der Wake-Word Datei (EDIT: wobei die im Client selbst liegt, also unwahrscheinlich).

**Comment by cap-blackbeard** [comment]
Der Web-Client auf dem iPhone und der Web-Client auf dem Windows-PC laden wieder das WakeWord! Und ich kann alles auch wieder von extern erreichen. Scheinbar hat mein eingebundener alter SEPIA-Ordner im docker-container ordentlich Unruhe verursacht.

Aber der DIY-Client mag immer noch nicht die WakeWord v2.1.
"Hey Sepia" v1.9 läuft sofort.
"Hey Sepia" v2.1 erzeugt denselben Fehler wie "JARVIS" v2.1.

By the way:
Das Problem mit dem Chromium-Browser besteht immer noch? Ich habe ja als OS Bullseye installiert. Nachdem ich jetzt Dein downgrade-script durchgeführt habe, funktioniert zumindest die stt-Erkennung wieder.

**Comment by fquirin** [comment]
> Der Web-Client auf dem iPhone und der Web-Client auf dem Windows-PC laden wieder das WakeWord! Und ich kann alles auch wieder von extern erreichen

Nice :-)

> Aber der DIY-Client mag immer noch nicht die WakeWord v2.1.

😢, also die gleichen, die aber auf dem iPhone funktionieren ja?

> Nachdem ich jetzt Dein downgrade-script durchgeführt habe, funktioniert zumindest die stt-Erkennung wieder

Das, was die ältere Version von Chrome installiert? Ja, irgendwie hat die Raspberry Pi Foundation leider die Google APIs komplett entfernt in neueren Versionen, so dass der SEPIA offline STT-Server zwingend nötig ist.

**Comment by cap-blackbeard** [comment]
> die aber auf dem iPhone funktionieren ja?

Ja. Das ist ja das frustrierende dabei! Der PC und das iPhone können beide die v2.1 laden. Nur der DIY-Client nicht.

**Comment by fquirin** [comment]
Das ist schon sehr merkwürdig, denn der Code ist ja genau der gleiche :-/. Das ist jetzt alles v0.25.0 richtig?

**Comment by cap-blackbeard** [comment]
> Das ist jetzt alles v0.25.0 richtig?

richtig.
Ich installiere den DIY-Client nochmal komplett neu.
Welche OS-version schlägst Du vor bzw. hast Du am laufen?

**Comment by fquirin** [comment]
Ich habe sowohl Bullseye als auch Buster laufen, die Empfehlung in den DIY Client Docs ist noch "32Bit Buster ('Legacy')", weil es häufiger getestet wurde.

Ich frage mich gerade ob das Problem eventuell der API Key ist. Wenn man den zu oft benutzt sperrt Picovoice neue Geräte für glaube ich 30 Tage. Ich weiß aber nicht mehr was dann für ein Fehler kommt, eigentlich würde ich dann "Invalid Key" erwarten. Da die eine "Device ID" im Browser Cache speichern ist leider jeder Cache-Clear = 1 neues Device. Bei 3 verschiedenen Devices wird gesperrt.

Guck mal in der Picovoice Console, was da über deinen Key steht.

**Comment by cap-blackbeard** [comment]
> Guck mal in der Picovoice Console, was da über deinen Key steht.

Monthly Active Users (1 of 3)

**Comment by fquirin** [comment]
> Monthly Active Users (1 of 3)

Also auch nicht die Antwort :-/

> Ich installiere den DIY-Client nochmal komplett neu.

Mehr fällt mir jetzt auch gerade nicht ein :-(

**Comment by cap-blackbeard** [comment]
Komplett andere Hardware (aber wieder n Raspi 3b), komplett neu installiert und der wieder selbe Fehler.
Spracherkennung klappt, Sprachausgabe klappt.
Und jetzt?

**Comment by cap-blackbeard** [comment]
Kann der Fehler mit der Hardware zusammenhängen? Bisher benutze ich den RPI 3b. Ich denke, ich installiere mal den Client auf meinem 4er. Mal gucken, was dann passiert.

**Comment by fquirin** [comment]
Ich habe den Client jetzt schon länger nicht mehr auf dem RPi3 ausprobiert, was mich allerdings wundert ist, dass der Fehler nur bei dem 2.1er WW auftritt. Von den Resourcen müsste das 1.9er eigentlich am anspruchsvollsten sein (da wurde von Picovoice versehentlich zu viel Memory reserviert). 

Ich frage mich, ob das irgendwie mit der Authentifizierung der 2.1 Lib zu tun haben kann. Die muss sich einmal mit dem Picovoice Server verbinden, damit die im Rahmen des free-Tiers aktiviert werden kann.

**Comment by cap-blackbeard** [comment]
Und wie schaffe ich diese Verbindung? Hört sich plausibel an.

**Comment by fquirin** [comment]
Das macht die Porcupine Lib automatisch (und geheim, was mich eigentlich nervt), ich weiß aber nicht wie die reagiert, wenn sie keine Internetverbindung hat oder keine Verbindung zum Picovoice Server herstellen kann. Gibt es vielleicht eine Firewall bei dir, die die Verbindung ablehnen könnte?

**Comment by cap-blackbeard** [comment]
Ich habe PiHole am laufen. Aber raus kommt eigentlich alles.

**Comment by fquirin** [comment]
Kannst du den Client eigentlich mit der remote debugger Funktion starten? So dass wir auf den Chrome direkt gehen können und dann die Dev Konsole (F12) checken?

**Comment by cap-blackbeard** [comment]
Kann ich bestimmt. Was, wo, wie genau?

**Comment by fquirin** [comment]
🙂 In `sepia-client/setup.sh` gibt es die Option `ENABLE remote debugging mode`. Danach steht auch grob, was man machen muss. Wenn man den Client damit startet, kann man theoretisch mit einem anderen Chrome/Chromium Gerät per `chrome://inspect/#devices` auf den laufenden SEPIA DIY remote zugreifen als wenn es ein Browser Fenster wäre. Manchmal dauert es etwas, bis das Gerät angezeigt wird und eventuell muss man im eigenen Chromium noch die URL zulassen. Online findet man dazu aber auch ein paar Tutorials ^^.

**Comment by cap-blackbeard** [comment]
> laufenden SEPIA DIY remote zugreifen als wenn es ein Browser Fenster wäre.

ich denke ich bin drauf. Und jetzt?

**Comment by fquirin** [comment]
> ich denke ich bin drauf. Und jetzt?

F12 um die developer console zu öffnen und dann mal über `settings - Hey SEPIA` die verschiedenen wake-words laden.
In der Konsole müssten dann Fehlermeldungen in rot auftauchen, die uns hoffentlich mehr Infos geben.

**Comment by cap-blackbeard** [comment]
Ja. Ich habe Fehlermeldungen. Kann ich diese kopieren, damit Du sie sehen kannst? Text markieren und kopieren funktioniert nämlich nicht.

**Comment by cap-blackbeard** [comment]
```
//build SEPIA Web Audio module for Porcupine
	function buildPorcupineSepiaWebAudioModule(porcupineVersion, wasmFile, keywordsArray, keywordsData, sensitivities, accessKey){
		var preLoad = {};
		if (wasmFile.match(/.*\.b64$/)){
			preLoad.wasmBase64 = wasmFile;		//e.g. 'xtensions/picovoice/porcupine-19.b64'
		}else{
			preLoad.wasmFile = wasmFile;		//e.g. '<assist_server>/files/wake-words/porcupine/porcupine-14.wasm'
		}
		var porcupineLanguage = "";
		if (porcupineVersion.indexOf("_") > 0){
			var ppvAndLang = porcupineVersion.split("_");
			porcupineVersion = ppvAndLang[0];
			porcupineLanguage = ppvAndLang[1].toLowerCase();
		}
		var keywordsRemoteLocation = SepiaFW.config.replacePathTagWithActualPath("<assist_server>/files/wake-words/porcupine/");
		var porcupineWorker = {
			name: 'porcupine-wake-word-worker',
			type: 'worker',
			preLoad: preLoad,
			settings: {
				onmessage: function(msg){
					if (msg && msg.keyword){
						broadcastWakeWordTrigger(msg.keyword);
					}
				},
				onerror: function(err){
					var errMsg = (err && err.message? err.message : "?");
----------------------->		SepiaFW.debug.error("Porcupine: " + errMsg);    <----------------      z.B. ist diese Zeile mit einem roten X als Fehler markiert
					SepiaFW.ui.showPopup("Porcupine error: " + errMsg);
					broadcastWakeWordError(errMsg);
					WakeTriggers.stopListeningToWakeWords();
				},
				//sendToModules: (doUseWaveEncoder? [waveEncoderIndex] : []),
				options: {
					setup: {
						inputSampleRate: 16000,		//TODO: load from somewhere else
						inputSampleSize: 512,		//TODO: 	"	  "
						//bufferSize: 512,			//this has no effect yet (samples will be processed in 'inputSampleSize' chunks)
						version: porcupineVersion,		//e.g. 1.4, 1.5, 1.6, 1.9, 2.0 or 14, 15, ...
						keywords: keywordsArray, 		//e.g. ["Hey SEPIA"] or ["Computer", "Jarvis", "Picovoice"]
						keywordsData: keywordsData,
						sensitivities: sensitivities,
						porcupineLanguage: porcupineLanguage,	//v2.0: "en", "de", "es", "fr"
						porcupineAccessKey: accessKey,
						keywordsRemoteLocation: keywordsRemoteLocation	//alternative location for "server: xy" keywords
					}
				}
			}
		};
```

**Comment by fquirin** [comment]
A screenshot of the actual error message would be god if you can't copy the console text since we need to know the reason why 'porcupine-wake-word-worker' crashed (the value of `errMsg`). The code above is just the module interface I wrote.

**Comment by cap-blackbeard** [comment]
![image](https://user-images.githubusercontent.com/97520765/202919960-86ad0822-a6ac-4a58-892a-8ecf4fefaa3c.png)

**Comment by fquirin** [comment]
Ty, I see a very interesting log entry: "[ERROR] failed to parse AccessKey: ..." (and then your key, you might want to change it later ^^). Weird. Maybe there is some copy paste issue with hidden text-format bytes (Windows does that sometimes when you copy non-UTF-8 text or something).
Huch, ich bin ins Englische abgedriftet =) egal.

Versuch mal bitte über den remote access the Key ins Feld einzugeben. Der aktuelle kommt aus der settings Datei oder?
[EDIT] Also ich meine den remote Chrome. Einfach in settings navigieren und da erst den Key löschen, speichern, dann neu eingeben.
[EDIT 2] Die Anführungszeichen kommen nur aus der Fehlermeldung oder? ^^

**Comment by cap-blackbeard** [comment]
> Der aktuelle kommt aus der settings Datei oder?

Ja. Das tut er.



> Versuch mal bitte über den remote access the Key ins Feld einzugeben.

Und jetzt klappt es tatsächlich!!! 
Und wo habe ich den Fehler gemacht???

**Comment by fquirin** [comment]
> Und jetzt klappt es tatsächlich!!!
Und wo habe ich den Fehler gemacht???

Verrückt 😖. Hast du den Key über Windows per copy-paste in ein Linux Terminal kopiert?
Ich hatte das Problem jetzt schon länger nicht mehr, aber früher hatten Windows und Linux unterschiedliche Text encodings und auch Heute noch unterschiedliche end-of-line (EOL) Zeichen (\n (Linux) und \n\r (Windows)), was mir oft Linux Bash Skripte kaputt gemacht hat aus "mysteriösen" Gründen, wenn ich die in Windows geschrieben hatte 😠. Manchmal gibt es aber auch Probleme zwischen den Terminals.
Was genau hier jetzt das Problem war ist schwer zu sagen, da der Key selbst ja eigentlich keine besonderen Zeichen enthält und auch keine EOL Zeichen normalerweise.

**Comment by cap-blackbeard** [comment]
> Hast du den Key über Windows per copy-paste in ein Linux Terminal kopiert?

Ja klar. 
Zu Beginn der Diskussion hatte ich ja noch den doppelten "alten" Ordner im Server. Ggf. wurde die erste Meldung nach dem Update dadurch ausgelöst? Dann, nach etlichen Neuinstallationen des Clients habe ich immer vom Windows-PC per Putty die settings.js editiert.
Jetzt habe ich den Key im DiY-CLient komplett gelöscht, gespeichert und den Client neu geladen. Dann habe ich über nen anderen Raspberry den Key in die settings.js des DiY-Clients eingetragen und den Client komplett neu gestartet. Und siehe da... das WakeWord wurde geladen !!!

Herzlichen Dank für Deine Geduld !!!

Ps.: Dann bleibt jetzt mehr Zeit um das KODI-Projekt weiter zu betreiben.

**Comment by fquirin** [comment]
> Dann, nach etlichen Neuinstallationen des Clients habe ich immer vom Windows-PC per Putty die settings.js editiert.

Eigentlich mache ich das genau so, deswegen verstehe ich das Problem nicht ganz.

> Herzlichen Dank für Deine Geduld !!!

Kein Problem. Mich würde natürlich schon interessieren, was man jetzt machen könnte, um das Problem in Zukunft zu vermeiden 😅. Vielleicht kann ich die Fehlermeldung irgendwie verbessern 🤔 

> Dann bleibt jetzt mehr Zeit um das KODI-Projekt weiter zu betreiben.

😎
