### ISSUE TITLE
DIY Client Soundkarte

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#209]
Hallo Florian,
nach der kompletten Neuinstallation des DIY-Clients wird die WM8960 Audio HAT Karte nicht benutzt.
`sudo alsamixer` zeigt mit ID 1 seeed-2mic-voicecard an
`pacmd list-cards` zeigt aber nur das HDMI-Display `1 card(s) available.         index: 0       name: <alsa_card.platform-3f902000.hdmi>`

Ich war so mutig, Raspbian lite Bullseye mit der `sepia-client-rpi.sh dev` Installation benutzen zu wollen. 

Hast Du ne Idee?

Grüße
Christian

**Comment by fquirin** [comment]
Hi Christian,

was ist der Output von `aplay -l`?

Die WM8960 HATs reagieren traditionell immer etwas allergisch auf Linux Kernel Updates :-| 
Welchen Kernel hast du gerade? (`uname -a`)

Versuch mal das alternative Git repository:
```
cd ~/install/
rm -rf seeed-voicecard
git clone https://github.com/HinTak/seeed-voicecard
cd seeed-voicecard
```

Und dann je nach Kernel z.B.:
```
git checkout v5.19
sudo ./install.sh
```

**Comment by cap-blackbeard** [comment]
> was ist der Output von `aplay -l`?
`card 0: vc4hdmi [vc4-hdmi]`
`card 1: seeed2micvoicec [seeed-2mic-voicecard]`



> Welchen Kernel hast du gerade? (`uname -a`)
`Linux SEPIAClient 5.15.74-v7+ #1595 SMP Wed Oct 26 11:03:05 BST 2022 armv7l GNU/Linux`


Rest probiere ich später...

**Comment by fquirin** [comment]
> `card 0: vc4hdmi [vc4-hdmi]`
`card 1: seeed2micvoicec [seeed-2mic-voicecard]`

Das sieht eigentlich ganz gut aus. Versuch mal:
```
cd ~/install
bash update_rpi_audio_boot.sh
```

Oder manuell: `dtparam=audio=off` via `sudo nano /boot/config.txt` setzen.
Alternativ könnte man auch versuchen das Standardgerät zu ändern via `sudo raspi-config -> System -> Audio`.

**Comment by cap-blackbeard** [comment]
> Das sieht eigentlich ganz gut aus. Versuch mal:
> 
> ```
> cd ~/install
> bash update_rpi_audio_boot.sh
> ```
> 
> Oder manuell: `dtparam=audio=off` via `sudo nano /boot/config.txt` setzen.

Ohne Erfolg. Aber so wie ich das verstehe wird hier "nur" der onboard-Chip deaktiviert?

> Alternativ könnte man auch versuchen das Standardgerät zu ändern via `sudo raspi-config -> System -> Audio`

Die WM8960 wird hier nicht aufgelistet. Gib nur den Eintrag: `0 MAI PCM i2s-hifi-0`.


Jetzt habe ich den Client nochmal komplett neu installiert. Bzw. bei der Installation der Soundkarte fällt mir gerade auf:

`Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.74-v7+ -C /lib/modules/5.15.74-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build......(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.15.74-v7+ (armv7l)
Consult /var/lib/dkms/seeed-voicecard/0.3/build/make.log for more information.
setup git config
git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint:   git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint:   git branch -m <name>
Initialized empty Git repository in /etc/voicecard/.git/
git add --all
git commit -m "origin configures"
[master (root-commit) bc2513f] origin configures
 7 files changed, 1482 insertions(+)
 create mode 100644 ac108_6mic.state
 create mode 100644 ac108_asound.state
 create mode 100644 asound_2mic.conf
 create mode 100644 asound_4mic.conf
 create mode 100644 asound_6mic.conf
 create mode 100644 dkms.conf
 create mode 100644 wm8960_asound.state
Created symlink /etc/systemd/system/sysinit.target.wants/seeed-voicecard.service → /lib/systemd/system/seeed-voicecard.service.`

**Comment by cap-blackbeard** [comment]
> cd ~/install/
> rm -rf seeed-voicecard
> git clone https://github.com/HinTak/seeed-voicecard
> cd seeed-voicecard

Das schein zu funktionieren.

> git checkout v5.19

Damit kann ich nichts anfangen `git checkout v5.15` oder auch `git checkout v5.15.74-v7+` ergeben nur error.

Aber `sudo ./install.sh` das scheint trotzdem zu klappen. Denn jetzt schreibt das script:
`Building module: cleaning build area... make -j4 KERNELRELEASE=5.15.74-v7+ -C /lib/modules/5.15.74-v7+/build M=/var/lib/dkms/seeed-voicecard/0.3/build..... cleaning build area... DKMS: build completed....`

So.. jetzt kommt auch das beliebte: "Ready for setup" 👍 

Vielen Dank

**Comment by fquirin** [comment]
> Damit kann ich nichts anfangen git checkout v5.15 oder auch git checkout v5.15.74-v7+ ergeben nur error.

Es gibt nicht für alle Kernels einen branch. Aber der master hat ja scheinbar funktioniert :-)

> So.. jetzt kommt auch das beliebte: "Ready for setup" 👍

🥳
