### ISSUE TITLE
docker update :latest

### ISSUE THREAD

**Issue by cap-blackbeard** [SEPIA-Framework/sepia-docs#211]
Hallo Florian,
im docker hub steht zwar, dass die aktuelle ServerVersion die v2.7.0 sein soll. Aber wenn ich das `sepia/home:latest` image lade, dann startet bei mir immer ein v2.6.2 Server.
`Running SEPIA Assist (sepia-assist-v2.6.2.jar)
SUCCESS
Running SEPIA WebSocket Chat (sepia-chat-v1.3.4.jar)
Running SEPIA Teach (sepia-teach-v2.2.4.jar)`

Selbst, wenn ich das `sepia/home:v2.7.0_amd64_auto` lade, dann startet nur der Server v2.6.2.

Ist das ein Fehler von mir oder sind im docker hub für die `linux/amd64` Geräte die falschen Dateien hochgeladen?

Grüße
Christian

**Comment by fquirin** [comment]
Hi, ich prüfe das noch mal, aber die müssten eigentlich korrekt sein 🤔. Brb.

**Comment by fquirin** [comment]
Also hab den Container noch mal frisch aus dem Docker HUB geladen, sieht alles gut aus, v2.7.0.

Nutzt du vielleicht ein altes Start-Script, wo die 2.6.2 Version hard-coded ist?

**Comment by cap-blackbeard** [comment]
Könnte sein.
Wo finde ich das Start-Script? Was genau meinst Du damit?
Ich benutze Portainer um die Container zu managen.

**Comment by cap-blackbeard** [comment]
Meinst Du den docker run Befehl?
Das sieht bei mir ja so aus:
![image](https://user-images.githubusercontent.com/97520765/200688384-453c27e1-4250-4440-8e59-ceeee92cf7be.png)

**Comment by fquirin** [comment]
Hm, also als image steht da ja ganz klar "sepia/home:latest". Was sind denn noch für volumes eingebunden? Vielleicht überschreibt ein pre v2.6.2 volume den ganzen SEPIA Ordner mit den alten Daten. Das Dateisystem wurde in v2.6.2 vereinfacht, damit Updates in Zukunft einfach über den pull des neusten Images laufen können, aber damit das klappt müssen ältere Container einmal per Hand aktualisiert werden:
https://github.com/SEPIA-Framework/sepia-docs/wiki/SEPIA-inside-virtual-environments#update-your-container

**Comment by cap-blackbeard** [comment]
> Vielleicht überschreibt ein pre v2.6.2 volume den ganzen SEPIA Ordner mit den alten Daten.

Nö glaube ich nicht.

![image](https://user-images.githubusercontent.com/97520765/200916909-2ea285b9-79dd-4c87-baf5-e65c53185d58.png)

Aber zur Sicherheit werde ich nochmal die Schritte in der Anleitung 

> https://github.com/SEPIA-Framework/sepia-docs/wiki/SEPIA-inside-virtual-environments#update-your-container

durchgehen.
Außerdem werde ich nochmal versuchen, ob doch ein Unterschied darin besteht, ob ich das Image per Portainer lade oder per Terminal und run-Befehl.

**Comment by cap-blackbeard** [comment]
> https://github.com/SEPIA-Framework/sepia-docs/wiki/SEPIA-inside-virtual-environments#update-your-container

Also scheinbar lag hier irgendwo der Fehler. Jetzt läuft 2.7.0
Mal gucken, wie es sich beim nächsten Update verhält.

Herzlichen Dank!

**Comment by fquirin** [comment]
@cap-blackbeard Im Screenshot oben ist noch der ganze `SEPIA` Ordner eingebunden, das ist das Problem dass ich meinte. Pre v2.6.2 war es so, dass alle Dateien des Users auch in diesem Ordner lagen, d.h. ein Update war im Grunde der Austausch des ganzen Ordners (und nachträglich eine Widerherstellung der User Daten). Ab v2.6.2 sind alle User-Daten in den `sepia-home-data` Ordner ausgelagert worden, so dass der Kern einfach ausgetauscht werden kann. Kurz gesagt heißt das, so lange der Ordner `SEPIA` noch als Volume eingebunden ist, nutzt der Container die Version, die dort drin steckt.
Ich würde die Daten in dem Volume einmal sichern und das Volume dann einfach entfernen.

**Comment by cap-blackbeard** [comment]
Ok ich verstehe. Mir war nicht klar, dass der Container dann nur noch mit dem `sepia-home-data` Ordner gestartet wird. Ich war tatsächlich der falschen Meinung, dass beide Ordner benötigt werden.
