### ISSUE TITLE
Login to DYI Client failed

### ISSUE THREAD

**Issue by tlrider99** [SEPIA-Framework/sepia-docs#221]
Hi Florian,

jetzt läuft der Client auf nem Raspi3+ mit nem 2Mic Respeaker board.
Ich höre " ready for setup" . Ich kann den Client vom Server aus erreichen ping all bringt mir die Infos:
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","msg":"Hello World"}}
Wenn ich mich aber versuche einzuloggen kommt folgender Fehler:
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","sepia-login":{"note":"loginFail"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","sepia-login":{"note":"loginFail"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","msg":"Logging in with new user: [uid1007]. Plz wait."}}
Broadcaster response: "sent"
Das Gleiche auch mit dem Admin User.
Hast du eine Idee was ich falsch mache?

Grüße
Dirk

**Comment by fquirin** [comment]
Hi Dirk,

dafür kann es mehrere Gründe geben:
- Server ist nicht erreichbar:
  - Falsche URL
  - Server offline
  - Zugriff geblockt, z.B. wegen HTTP/HTTPS mixed content
- Username/password sind falsch
- Irgendwelche internen Fehler

Tipp mal "call ping" ein, dann wird die Verbindung zum Chat-Server getestet.

**Comment by tlrider99** [comment]
Hi Florian,

das sieht meines Erachtens gut aus.
![image](https://user-images.githubusercontent.com/29237172/212312072-868c0698-3c3b-474b-9cae-b36d5b80ac25.png)

Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","ping-result":{"adr":"http://192.168.10.122:20723/ping","status":200,"data":{"result":"success","server":"SEPIA-Websocket-Server"}}}}
Broadcaster response: "sent"
Broadcaster event: {"broadcast":{"name":"sepia-client","data":{"deviceId":"o1","call":"ping"}}}

Mixed content wenn ich die Anleitung richtig verstanden habe, wird mit ws in der url umgangen, richtig?
Passwort/user sollte auch passen, mehrmals  probiert.

Das steht im log-clexi.out:
Local date/time at start: 11/01/2023, 08:21:36
Server with ID 'clexi-123' running at: http://127.0.0.1:8080
Hostname: localhost - SSL: false
CLEXI Xtensions loaded: 4

Hast du noch eine Idee?

**Comment by fquirin** [comment]
> das sieht meines Erachtens gut aus.

In der Tat

> Mixed content wenn ich die Anleitung richtig verstanden habe, wird mit ws in der url umgangen, richtig?

ja, bzw. so lange dein Control-HUB nicht über "https" läuft während deine Server URL "http" ist (analog wss und ws), sollte es da keine Probleme geben.

> Hast du noch eine Idee?

Ich habe mal die Log Meldung verbessert, vielleicht hilft uns das den Fehler zu finden. Du solltest in `~/clexi/www/sepia/scripts` eine Datei namens `sepiaFW.inputControls.cmdl.js` sehen. Ersetz die mal bitte durch die aus dieser ZIP: [sepiaFW.inputControls.cmdl.js.zip](https://github.com/SEPIA-Framework/sepia-docs/files/10411203/sepiaFW.inputControls.cmdl.js.zip)

**Comment by tlrider99** [comment]
Ich verstehe die Meldung tatsächlich nicht, denn ich bin mit dem User am Server angemeldet. UserID u. Passwort passen.
Ist meine Eingabe in den [] falsch?
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","sepia-login":{"note":"loginFail","error":"Login failed! - Wrong username or password."}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.25.0","deviceId":"o1","msg":"Logging in with new user: [uid1007]. Plz wait."}}
Broadcaster response: "sent"
Broadcaster event: {"broadcast":{"name":"sepia-client","data":{"deviceId":"o1","call":"login","user":"[uid1007]","password":"[11XXXXXXX]"}}}

Brauche ich einen neuen User je Client?

**Comment by fquirin** [comment]
Ach, ich sehe das Problem 😅, die [...] sind nur als Platzhalter gedacht, also aus [userId] wird uid1007, nicht [uid1007] 🙈. 
Eigentlich ein Klassiker, wie früher immer bei "ID" (ohne Anführungszeichen) ^^. Irgendwann mache ich dafür vielleicht mal ein Login via Pop-Up statt "Terminal" Eingabe, um solche Dinge zu vermeiden.

**Comment by tlrider99** [comment]
Kaum macht man es richtig. 
Sorry bin immer noch kein IT'ler. Irgendwann lerne ich es auch! 😅

**Comment by fquirin** [comment]
Es ist auch mehr meine naive Hoffnung, glaube ich, dass diese Platzhalter richtig verstanden werden 😅 . Vielleicht sollte ich ein Beispiel hinzufügen in der Hilfe.
Abgesehen davon, hat der Client jetzt eine bessere Fehlermeldung, also war das ganze nicht umsonst ;-)
