### ISSUE TITLE
How to set-up an apache vhost?

### ISSUE THREAD

**Issue by DevDorrejo** [SEPIA-Framework/sepia-docs#23]
Hello, i am looking how can i set up and apache vhost instead of Nginx?, thank you.

**Comment by fquirin** [comment]
Hi,

I'm not an expert for Apache web server but maybe this will help:
https://github.com/SEPIA-Framework/sepia-docs/wiki/Reverse-Proxy-Setup#apache-http-server-example-setup-for-sepia

regards

**Comment by DevDorrejo** [comment]
Thank you.

> Hi,
> 
> I'm not an expert for Apache web server but maybe this will help:
> https://github.com/SEPIA-Framework/sepia-docs/wiki/Reverse-Proxy-Setup#apache-http-server-example-setup-for-sepia
> 
> regards

i need to open the port of the proxy on my server and on my firewall?

**Comment by fquirin** [comment]
Do you want to access your SEPIA server from your local, private network or from "anywhere"?
For internal networks there is usually no firewall stuff required unless your system has some specific settings. For access from outside you need to forward port 20726 (default port for the proxy) inside your network router and point it to your Apache machine. Here is a bit more info:
https://github.com/SEPIA-Framework/sepia-docs/wiki/Network-Configurations

**Comment by DevDorrejo** [comment]
Hello, i have a VPS and do the next config:

Firewall: Open port 20726/tcp-udp 20727/tcp-udp, 80/tcp, 443/tcp

SEPIA-home root: /opt/sepia-server

Apacher-vhost: 

```
Define LOCATION /opt/sepia-server
Define HOST sepiawedc.duckdns.org

ProxyPass /${LOCATION}/assist/ http://${HOST}:20721/
ProxyPass /${LOCATION}/teach/ http://${HOST}:20722/

<Location /${LOCATION}/chat/>
ProxyPass http://${HOST}:20723/

RewriteEngine On
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule /messages/(.*) ws://${HOST}:20723/messages/$1 [P]
</Location>
```

**Comment by sepia-assistant** [comment]
Hi,

as I said I'm not very experienced with Apache but looking at your configuration I see 2 potential issues. The LOCATION field is (to my understanding ... I could be wrong here) not related to the physical location of the files but defines the URL path, e.g. `http://localhost:20726/LOCATION/assist/app/index.html` . It should be set to `LOCATION sepia` as seen in the example.

The actual physical path of your SEPIA folder should be "~/SEPIA" otherwise the start scripts might not work properly (shame on me but there are 2-3 places where "~/SEPIA" is hardcoded in the .sh files). Can you confirm that the server actually starts?

**Comment by DevDorrejo** [comment]
> Hi,
> 
> as I said I'm not very experienced with Apache but looking at your configuration I see 2 potential issues. The LOCATION field is (to my understanding ... I could be wrong here) not related to the physical location of the files but defines the URL path, e.g. `http://localhost:20726/LOCATION/assist/app/index.html` . It should be set to `LOCATION sepia` as seen in the example.
> 
> The actual physical path of your SEPIA folder should be "~/SEPIA" otherwise the start scripts might not work properly (shame on me but there are 2-3 places where "~/SEPIA" is hardcoded in the .sh files). Can you confirm that the server actually starts?

Yes, when i exec the run, everything is OK.

Changed all files to point to where i storage the folder (/opt/sepia-server), and open all the port from 20720-20727.

now is working,
[http://sepiawedc.duckdns.org:20721/tools/index.html](url)

but what is the default user, i change the user password to 12345678, but every time said work password or user:

username: admin
password: 12345678

i think i changed it using the second option on the setup.

**Comment by sepia-assistant** [comment]
> Changed all files to point to where i store the folder (/opt/sepia-server), and open all the port from 20720-20727.
> 
> now is working,
> [...]
> 
> but what is the default user, i change the user password to 12345678, but every time said wrong password or user:
> 
> username: admin
> password: 12345678

Hi, glad to hear its working now!
The default admin username is `admin@sepia.localhost` (including the @.. part) or `uid1003`. The UID might change when you reset the password but the pseudo email address should always stay the same.
The first thing you should do after a successful setup is to create a new non-admin user as [mentioned here](https://github.com/SEPIA-Framework/sepia-installation-and-setup#next-steps).

**Comment by DevDorrejo** [comment]
> > Changed all files to point to where i store the folder (/opt/sepia-server), and open all the port from 20720-20727.
> > now is working,
> > [...]
> > but what is the default user, i change the user password to 12345678, but every time said wrong password or user:
> > username: admin
> > password: 12345678
> 
> Hi, glad to hear its working now!
> The default admin username is `admin@sepia.localhost` (including the @.. part) or `uid1003`. The UID might change when you reset the password but the pseudo email address should always stay the same.
> The first thing you should do after a successful setup is to create a new non-admin user as [mentioned here](https://github.com/SEPIA-Framework/sepia-installation-and-setup#next-steps).

Thank you can access now, but have the next issue when creating the user:

![image](https://user-images.githubusercontent.com/7697566/75787561-43329c80-5d3d-11ea-8712-f492987d3a86.png)

**Comment by sepia-assistant** [comment]
Ah yes, this is a security "feature" ^^. "not allowed to access server from outside the private network" means that certain actions in the Control-HUB are only allowed when you are in the local network of the server (e.g. IPs 192.168....). 
You have 2 options:
* either access the Control-HUB and server directly via the local IP of your server, e.g. `http://192.168.0.10:20721/tools/index.html` (replace IP accordingly)
* or if that is not possible, deactivate the security feature by editing the field `allow_global_dev_requests=true` in your server config `~/SEPIA/sepia-assist-server/Xtensions/assist.custom.properties`

**Comment by DevDorrejo** [comment]
Thank you, i created a user, how can i get info of the uid?, i put the password, but forget it immediately XD, and how can i manage the db? or can i change to mysql o postgresql?

**Comment by sepia-assistant** [comment]
=) If you remember the email address (fake or reak) you've used to create the user you can use it to login and check on settings page 3 what your UID is.
In your SEPIA folder there is a script as well: `SEPIA/scripts/get-es-user-stats.sh` that should give you email and UID of all users if I remember correct ;-)
MySQL or PostreSQL are not supported at the moment. SEPIA itself will require Elasticsearch to run. There is an alternative module for user accounts using DynamoDB, but that hasn't been tested for a while. In theory it could be replaced by any DB ... with some effort ^^

**Comment by DevDorrejo** [comment]
ok, thank you.

**Comment by sepia-assistant** [comment]
I've built a new function into the SEPIA Control HUB to check the existing user accounts, stay tuned for SEPIA v2.5.0 ;-)

**Comment by DevDorrejo** [comment]
Ok, thank you very much.
