### ISSUE TITLE
Login works on control hub but fails on client app

### ISSUE THREAD

**Issue by cinderblockgames** [SEPIA-Framework/sepia-docs#233]
It looks like the login page is sending to /sepia/assist/authentication from the control hub but to /sepia/sepia/assist/authentication from the client app.  I assume I messed something up, but I have no idea what it could be, since this is just a clean install with no changes.  Is there anywhere I can look to fix this?

**Comment by fquirin** [comment]
Hi,
can you please double-check your "hostname" setting that shows up in the login pop-up (you can press the "i" for more details).
It should be something like "localhost", "192.168.0.10" or preferably your proxy with SSL like "https://server-name.local:20726/sepia" or "https://my-domain.example/sepia".

**Comment by cinderblockgames** [comment]
Thank you!  That helped me find the settings.
