### ISSUE TITLE
No Login possible

### ISSUE THREAD

**Issue by stemeda** [SEPIA-Framework/sepia-docs#28]
Hey, 

I installed SEPIA (https://github.com/SEPIA-Framework/sepia-installation-and-setup#quick-start). I set the Admin password to a simple test password. Afterwards I open the login page (http://ip:20721/tools/index.html), type Username "Admin", the Password and Auth server "http://ip:20721".

The app says "Login fehlgeschlagen! - Username oder Password ist falsch.". The response is
```
HTTP/1.1 200 OK
Date: Sat, 04 Apr 2020 17:55:48 GMT
Access-Control-Allow-Origin: *
Access-Control-Request-Method: *
Access-Control-Allow-Headers: *
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.4.18.v20190429)

{"result":"fail","error":"400 or 500 bad request or communication error","code":"0"}
```

I tested with username "admin", "Assistant" and "assistant". The response from server is always same. I startet SEPIA with normal user and root.

Any hint what to do? Are there any log files? In the SEPIA folder, I can not see any.

**Comment by fquirin** [comment]
Hi :-)

The user name is not valid, have you seen this note?

> For testing purposes (only!) you can use the admin-acount to log-in, by default the ID is "admin@sepia.localhost" or "uid1003" (don't use the "assistant" account). The password has been set during setup.

**Comment by stemeda** [comment]
Oh, so simple. Thanks for you fast answer and this great project :-)
