### ISSUE TITLE
Weather Api Key not available ->  darksky.net closed 

### ISSUE THREAD

**Issue by hartm11** [SEPIA-Framework/sepia-docs#33]
It's not really a bug, just an information.
You have an integrated Weather Service.
Dark Sky has joined Apple. Since 31st of March there is **no API Key available anymore**.
Here the note in the blog: "_The API will continue to function through the end of 2021._"
See also  [https://blog.darksky.net/](url)

Best regards

**Comment by fquirin** [comment]
Hi and thanks for posting this.
Its really sad BUT I've already finished the new and improved weather service :grin: ... it will be part of the next updated and require no key at all :-)

**Comment by fquirin** [comment]
The new weather service is now available :-)
