### ISSUE TITLE
Clexi startet nicht auf dem Client

### ISSUE THREAD

**Issue by hartm11** [SEPIA-Framework/sepia-docs#36]
Hi zusammen,

vielleicht hat ja jemand eine Lösung, wie ich den Clexi auf dem Client zum laufen bekomme.
Stand bei mir ist:
Raspi mit Buster neu installiert.
Respeaker 4-Mic installiert
Sepia Client installiert

Während der Installation konnte ich keine Fehler sehen, aber :-)
im Clexi/log.out steht:
```
Server with ID 'clexi-123' running at: http://127.0.0.1:8080
Hostname: localhost - SSL: false
CLEXI Xtensions loaded: 3
/home/joerg/clexi/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100
    this._deviceId = this._socket.bindRaw(deviceId);
                                  ^

Error: ENODEV, No such device
    at Hci.init (/home/joerg/clexi/node_modules/@abandonware/noble/lib/hci-socket/hci.js:100:35)
    at NobleBindings.init (/home/joerg/clexi/node_modules/@abandonware/noble/lib/hci-socket/bindings$
    at process.nextTick (/home/joerg/clexi/node_modules/@abandonware/noble/lib/noble.js:60:24)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Ich vermute mal, es liegt am Raspi. Ist ein Raspi 2B+ und der hat kein Bluetooth.
Brauche ich auch nicht, nur weiß ich nicht, wie ich das umgehe oder abschalte.
Man könnte natürlich auch im Installationsscript den Fehler abfangen ;-)
Kann natürlich auch ein anderes Problem sein.
Wäre echt klasse, wenn jemand eine Lösung hat. Ich komme sonst nicht weiter.

**Comment by hartm11** [comment]
Hat mich ja nicht schlafen lassen :-)
Gelöst: Habe in clexi/settings.json die Zeile "ble-beacon-scanner" entfernt.

**Comment by fquirin** [comment]
Gibt es vielleicht einen Kommandozeilenbefehl mit dem man das vorher prüfen kann? Dann könnte ich es ins Installationsskript einbauen

**Comment by hartm11** [comment]
Ja, wenn ich folgendes in der Kommandozeile eingebe:
   `cat /sys/firmware/devicetree/base/model`
bekomme ich folgende Antwort:
   

> Raspberry Pi 2 Model B Rev 1.1

**Comment by fquirin** [comment]
Ah das geht natürlich auch :-) ... ich dachte erst an eine Abfrage, die den Bluetooth Support testet aber irgendwo mache ich eh schon einen Pi Versionscheck ... da könnte man ja ... ;-)
