### ISSUE TITLE
Anleitung/Vorschlag:  MQTT-Service an Node Red anbinden

### ISSUE THREAD

**Issue by hartm11** [SEPIA-Framework/sepia-docs#37]
Hallo zusammen,
ich habe mal eine Anleitung geschrieben, wie ich über den MQTT-Service eine Anbindung an Node Red hinbekomme. Ich finde die Lösung eigentlich ganz gut weil:
1. Ich definiere meine Geräte in Node Red (Lavalampe, Vitrine, ...)
2. Kurze Befehle möglich ("mqtt schalte die Lavalampe ein.", also kein "mqtt schalte das Licht der Lavalampe im Wohnzimmer ein" :-)
3. Ich kann mit einem Satz mehrere Geräte ein-/ausschalten ("mqtt schalte die Lavalampe, die Vitrine und die Leselampe ein"). Alle 3 Geräte werden dann eingeschaltet. Steht alles im Word-Dokument mit vielen Bildchen ;-)

Hier das Word-Dokument:
[Anleitung für die Anbindung über MQTT an Node Red.docx](https://github.com/SEPIA-Framework/sepia-docs/files/4589192/Anleitung.fur.die.Anbindung.uber.MQTT.an.Node.Red.docx)

**Comment by fquirin** [comment]
Hey, sehr cool 😎 :+1: 
Ich überlege gerade wo man das am Besten hinpacken könnte, so dass User direkt drauf zugreifen können ohne Word. Das SEPIA Wiki hier in GitHub hat leider keinen Image Upload und vom Format wäre das eher ein kleiner Blog Artikel :thinking:

**Comment by hartm11** [comment]
Wie wäre es denn mit einer pdf-Datei?

**Comment by fquirin** [comment]
PDF klingt gut, ich würde es aber am liebsten komplett ins Wiki übertragen, vielleicht dann mit der PDF als Anhang. Es gibt scheinbar einen kleinen Trick um Bilder hochzuladen ohne sie direkt ins Repository zu übertragen, ... ich teste Morgen mal ;-)

**Comment by capitaenz** [comment]
Hallo zusammen,
würde mir sehr gerne das Dokument mal ansehen, aber docx..!?
VG
Leif

**Comment by hartm11** [comment]
Hallo,
ja, wenn ich für mich was schreibe, kann ich es am schnellsten mit Word.
Hab den Vorschlag mal als pdf-Datei gedruckt. Ich denke das kann jeder lesen/öffnen.
Hier der Link zur pdf:
[Anleitung für die Anbindung über MQTT an Node Red.pdf](https://github.com/SEPIA-Framework/sepia-docs/files/4638756/Anleitung.fur.die.Anbindung.uber.MQTT.an.Node.Red.pdf)

Falls man nicht damit zurecht kommt, einfach alles bis zum ersten Node "empfSepiaTopics" (...abonniere alles von Sepia...) nachbauen und einen "debug"-Node hinten dranhängen. Dann kann man sehr schön in den debug-Nachrichten sehen, was und in welchem Format empfangen wird.

Viele Spaß

**Comment by sepia-assistant** [comment]
@hartm11 Danke für den PDF Upload :-)
Ich habe quasi last-minute entschieden die neuen MQTT Funktionen, die eigentlich für SEPIA v2.5.1 geplant waren doch noch ins v2.5.0 Update einzubauen. Dadurch verzögert sich gerade noch alles etwas aber ich denke es lohnt sich ^^. 

Eine Frage hätte ich dazu, vielleicht weißt du Rat :-) 

Bisher ist es so, dass der User (Smart Home Admin) in v2.5.0 neue Geräte erstellen kann im SEPIA Control HUB, die dann einem MQTT Kanal (Topic) lauschen (Präfix `sepia/smart-devices/` + [selbst definiert]) und bei State Änderungen ("Licht im Wohnzimmer auf 70%") dann diesen State im selben Kanal publizieren als `{ "state": 70 }` zum Beispiel.
Die Frage die ich mir hier stelle ist, ob zusätzlich noch weitere Infos in das Objekt sollten (type, room, etc.) oder ob die dem Node-Red (o.ä.) User eh durch den Kanal bekannt sind. 
Ich tendiere dazu das Objekt so klein wie möglich zu halten ;-)

**Comment by hartm11** [comment]
Hi,
ich habe mal versucht das zu erläutern wie es bei mir aufgebaut ist. Dazu habe ich eine pdf mit Bildchen erstellt, sonst hätte ich mir einen Wolf geschrieben.
Die ersten beiden Seiten zeigen es so, wie ich es bei mir eingestellt habe mit einer kurzen Beschreibung der Prefixe (ist vielleicht wichtig für eine Statusabfrage in Sepia. Alle Sonoffs sind bei mir mit Tasmota geflasht. Ich denke das nutzen auch die meisten, da Tasmota sehr viele Geräte abdeckt. Seite 3 zeigt den Group Topic. Den hast Du ev. noch nicht beachtet, ist aber eine nette Funktion.
Seite 4, endlich die Antwort auf Deine Frage :-D, und was mir sonst noch so dazu eingefallen ist.
[MQTT Modul Einbindung in Sepia.pdf](https://github.com/SEPIA-Framework/sepia-docs/files/4656551/MQTT.Modul.Einbindung.in.Sepia.pdf)

**Comment by sepia-assistant** [comment]
Cool, danke für die Erklärungen! :-)

Ein Zitat aus der PDF:

> Ja, es sollte mindestens der Raum mit drin sein, sonst weiß NodeRed nicht welches Gerät
angesprochen werden soll. NodeRed weiß ja im Prinzip nichts

Ich glaube hier gibt es 2 Ansätze. Die Informationen im Topic Namen zu haben oder im Payload. Der Topic Name könnte z.B. sein `sepia/smart-devices/light/livingroom/brightness`, damit wären dann alle relevanten Informationen schon definiert und der Kanal weiß auch, dass "70" -> 70% meint. Aus deiner PDF und der Frage nehme ich an, dass du eher den Fall bevorzugst bei dem der Topic einen ganzen Raum oder eine Gruppe definiert? Da würden diese Infos dann natürlich fehlen.

Im moment ist SEPIA's MQTT Connector so konzipiert, dass jedes Gerät einen eigenen Kanal hat. Das macht die Konfiguration etwas einfacher, wobei es glaube ich im Endeffekt aufs gleiche hinausläuft. Hier wird dann auch der Unterschied zum MQTT Demo Service klar, da ging es ja eher darum die SEPIA Befehle weiterzuleiten, bevor sie ausgewertet werden.

Soweit ich das gesehen habe kann NodeRed sowohl Topic als auch Payload beliebig parsen oder?

**Comment by hartm11** [comment]
Das mit den Gruppierungen ist nur eine Idee von mir. Ich selbst nutze "nur" einzelne Geräte steuern und den Group Topic. Finde ich irgendwie cool wenn ich rausgehe und nur einen Befehl habe "Alle Lichter aus".

Ja, NodeRed hat einige Parser in der Grundausstattung. Hier z.B. der, den ich für den MQTT-Service genutzt habe und der wichtigste Teil der NodeRed Beschreibung dazu:
![json parser](https://user-images.githubusercontent.com/64219122/82647743-ec8b7f00-9c16-11ea-8d75-31db9c79ff92.png)

> Konvertiert zwischen einem JSON-String und seiner JavaScript-Objektdarstellung in beide Richtungen.
**Eingaben**:  _payloadObjekt | String_
Ein JavaScript Objekt oder ein String.
**schema**:  _Objekt_
Ein optionales JSON Schema Objekt gegen das das JSON Objekt validiert wird.
**Ausgaben**:  _payloadObjekt | String_
Wenn die Eingabe ein JSON-String ist, wird versucht ihn in ein JavaScript-Objekt zu parsen..
Wenn die Eingabe ein JavaScript-Objekt ist, wird ein JSON-String erstellt. Der String kann optional gut formatiert werden.

Was man damit dann in NodeRed macht, bleibt jedem selbst überlassen.
Sollte der Aufbau des SepiaMQTT's der Gleiche sein, den das Gerät auch abonniert hat, braucht man gar nichts mehr in NodeRed machen (ev. noch die Rückmeldung/Status auswerten). Das ist dann der Idealfall. Ansonsten ist es relativ einfach den SepiaMQTT in den entsprechenden Kanal umzuleiten. Das habe ich ja quasi beim SepiaMQTT-Service auch schon so gemacht.

Der GroupTopic wird, denke ich, dann auch nutzbar sein. Man muss eben nur ein Pseudo-Gerät definieren wie `device: "alle Lampen"` und dann aus NodeRed den entsprechenden GroupTopic versenden. Das sollte eigentlich funktionieren.

**Comment by sepia-assistant** [comment]
Ok super, danke :+1: . Ich werde für v2.5.0 dann jetzt nichts mehr ändern daran und mal gucken wie gut es in der Praxis funktioniert :-)

**Comment by fquirin** [comment]
v2.5.0 ist online. Eine Anleitung folgt noch, Feedback erwünscht :-D

**Comment by fquirin** [comment]
Anleitung für die neue MQTT Integration ist nun auch online :-)

https://github.com/SEPIA-Framework/sepia-docs/wiki/Smart-Home-Controls#tutorial-sepia-internal-multi-hub

Ich überlege gerade die PDF von Oben ([Anbindung über MQTT an Node.Red](https://github.com/SEPIA-Framework/sepia-docs/files/4638756/Anleitung.fur.die.Anbindung.uber.MQTT.an.Node.Red.pdf)) irgendwo dort auch zu verlinken oder ob das eigentlich in eine eigene Sektion gehört, die sich eher mit SEPIA Services beschäftigt :thinking:

**Comment by hartm11** [comment]
Meiner Meinung nach sollte es in den Bereich Services. Es bezieht sich zwar beides auf MQTT, sind aber zwei verschiedene Ansätze/Wege für die MQTT Integration.

**Comment by Smarthome-Creator** [comment]
Hallo,

da ihr zwei ja hier eine Menge Fachchinesisch sprecht, könnt ihr mir vielleicht weiterhelfen. Ich bin nun seit release 2.5.0 fleißig dabei mein Smarthome einzurichten, da jetzt auch die Wake Word Erkennung um Welten besser läuft. Jetzt bin ich auf ein Problem gestoßen, bei dem ich mir nicht ganz zu helfen weiß. 

In openHAB werden manche Things als String definiert. So zum Beispiel die ganzen Aktionen die man für den Harmony HUB anlegt. Diese Strings simulieren am Ende eine Fernbedienung, das Problem ist jetzt das Sepia diese Strings nicht als "Aktion" interpretieren kann.

Als Beispiel: Ich habe eine Aktion die sich "Fernsehen gucken" nennt und eine andere die sich "Film über Fernseher gucken" nennt. Bei der zweiten Aktion wird zusätzlich die Soundbar eingeschaltet.

Dasselbe habe ich bei meinem über den Harmony HUB gesteuertem TV. Die Fernbedienung sollte lauter, leiser und sowas können. Aber auch das geht nicht, da Sepia hier Probleme hat den Status zu ändern.

Ich kann also Sepia nicht beibringen zwischen verschiedenen Aktionen hin und her zu wechseln, bzw. ergibt sich hieraus meine eigentliche Frage, hat einer von euch beiden eine Idee wie ich das Sepia beibringen kann?

**Comment by hartm11** [comment]
Hallo, ich bin auch "nur ein Anwender" und kenne mich mit openHAB nicht so aus. So wie ich Dein Problem verstehe, hast Du ein **Gerät** definiert, das "**Fernseh gucken**" heißt. Wenn es so ist, reicht der Befehl dann nicht aus, da daraus nicht hervor geht (aus SEPIA-Sicht): Soll ich das Gerät "Fernseh gucken" ein- oder ausschalten.
Vom (einfachen) Prinzip versucht eine Sprachsteuerung den gesprochenen Satz audzudröseln in Ort, Gerät und Aktion. Der Rest wird dann weggelassen. Dann kommt folgendes ungefähr raus:
Selbsdefiniertes Gerät:  Glotze = TV
"Schalte die Glotze im Wohnzimmer ein" -> Ort: Wohnzimmer, Gerät: TV, Aktion: ON
Bei einem Gerät, das "_Fernsehen gucken_" heißt, (also dem TV zugeordnet) käme dann folgendes raus:
"Ich möchte Fernsehen gucken im Wohnzimmer" -> Ort: Wohnzimmer, Gerät: TV, Aktion: ????

Versuch es mal testweise mit "Fernsehen gucken einschalten". Wenn das funktioniert, hast Du zwar  den Grund aber noch nicht die Lösung gefunden ;-) 

Aktionen sind (sprachlich) überwiegend: "_... einschalten_",   _"... auf 22 Grad Celsius_" oder "_... auf 70%_"

**Comment by fquirin** [comment]
>In openHAB werden manche Things als String definiert. So zum Beispiel die ganzen Aktionen die man für den Harmony HUB anlegt. Diese Strings simulieren am Ende eine Fernbedienung, das Problem ist jetzt das Sepia diese Strings nicht als "Aktion" interpretieren kann.
[...]
Als Beispiel: Ich habe eine Aktion die sich "Fernsehen gucken" nennt und eine andere die sich "Film über Fernseher gucken" nennt. Bei der zweiten Aktion wird zusätzlich die Soundbar eingeschaltet.

Hi,
also ich bin nicht sicher ob ich das Setup ganz richtig verstanden habe, aber generell ist SEPIA erstmal egal wie deine openHAB Geräte/Things/Items/etc. heißen, das kannst du in SEPIA (oder über die openHAB "sepia-..." tags) frei neu definieren. Wichtig ist nur, dass das openHAB "Thing" was du steuern willst einen Kanal hat der als "Item" (channels -> linkedItems) Befehle empfangen kann.
Ist "Fernsehen gucken" ein "Item"?

**Comment by Smarthome-Creator** [comment]
@fquirin ,
das ist leider genau die Krux an der ganzen Sache. Der Harmony HUB simuliert einfach gesagt eine universal Fernbedienung. Diese wird in openHAB als "String" angelegt.

Als Beispiel: Die Aktion "TV gucken" beinhaltet das einschalten des Fernsehers und das auswählen der input source "TV". 

Die Aktion "PS4 spielen" würde die Abfolge TV einschalten - Soundbar einschalten - HDMI Source der PS4 auswählen beinhalten.

Den Harmony HUB braucht man quasi um nicht Smarthome fähige Geräte "smart" zu machen.

Und ich glaube genau diese "Strings" kann Sepia eben nicht auflösen. Wenn ich versuche im Smarthome Hub eben so eine Aktion zu erstellen und diese testen zu wollen bekomme ich dann eine Fehlermeldung ( cannot switch device state due to unknown old state... ).
Um es also kurz zu beschreiben kann Sepia die emulierte Fernbedienung nicht ansteuern da Sepia den "State Type" nicht erkennen kann. 

Jetzt ist halt einfach nur die Frage ob man diesen State Type noch mit einbauen kann oder ob wir hier an eine technische Grenze gelangt sind?

**Comment by fquirin** [comment]
Ist der Harmony HUB als "Item" in openHAB eingerichtet?
Kannst du über das REST Interface von openHAB besagte Befehle auslösen?

>Jetzt ist halt einfach nur die Frage ob man diesen State Type noch mit einbauen kann oder ob wir hier an eine technische Grenze gelangt sind?

Wenn openHAB es steuern kann, dann kann es auch SEPIA ... behaupte ich jetzt einfach mal ;-)

**Comment by Smarthome-Creator** [comment]
Na du fragst mich ja Sachen... ich habe keine Ahnung wie man das macht. Google hilft mir da leider auch nicht weiter. Irgendwas mit curl... riesen Befehl hinten dran und trortdem keine ordentliche Erläuterung wie man das macht und wo man das überhaupt reintippen soll. Das ist chinesisch für mich.

Aber erstmal kann ich sagen ja der Harmony Hub ist als Item eingerichtet.

**Comment by fquirin** [comment]
Genau was ich brauchte :-) Ich habe eine Idee, die vielleicht klappen könnte.
Versuch mal folgenden Befehl über die Teach-UI zu speichern:

Smart device: `<tv>;;HarmonyFB`
Action: `<set>`
Value: `{"type":"text_raw","value":"Fernsehen gucken"}`

![image](https://user-images.githubusercontent.com/18550513/85329477-e537e980-b4d2-11ea-87df-dd8624a3f033.png)

**Comment by hartm11** [comment]
Meinst Du das geht? Was für ein Wert wird dann unter Action übertragen? --Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 22.06.20, 21:55 schrieb Florian Quirin <notifications@github.com>:

   
  Genau was ich brauchte :-) Ich habe eine Idee, die vielleicht klappen könnte. Versuch mal folgenden Befehl über die Teach-UI zu speichern: 
  Smart device: <tv>;;HarmonyFB Action: <set> Value: {"type":"text_raw","value":"Fernsehen gucken"}

**Comment by fquirin** [comment]
>Meinst Du das geht? Was für ein Wert wird dann unter Action übertragen?

Der Wert für "Action" is fast egal in diesem Fall ("on" und "set" sollten auf jeden Fall gehen, eventuell sogar "off"), da er von Value überschrieben wird. Wenn ich die Daten des REST Endpoints richtig interpretieren empfängt das Harmony "Item" die Strings als value und der Befehl sendet dann value="Fernsehen gucken".

**Comment by fquirin** [comment]
Fortsetzung des Harmony Themas: https://github.com/SEPIA-Framework/sepia-docs/issues/53
