### ISSUE TITLE
Keine Clexi-Verbindung zum Client möglich

### ISSUE THREAD

**Issue by hartm11** [SEPIA-Framework/sepia-docs#38]
Hallo zusammen,
wie sollte es sein, ich habe ein Problem :-)  Ich bekomme keine Verbindung vom Hub zu Client hin.
Mein bisheriger Ablauf:
- auf dem Raspi 2B alles neu installiert
(Raspbian, Respeaker 4-Mic und den Client)
- alle nötigen Parameter eingestellt, den Rest
auf default gelassen (z.B. clexi-123, oder device = o1, ...)

In clexi/settings.json den Eintrag "ble-beacon-scanner" entfernt und in
www/sepia/settings.js den Eintrag "useBluetoothBeacons" auf false gesetzt.

Nach dem Neustart komme ich bis zum "Ready4Setup". Soweit scheint auch alles zu laufen.
Wenn ich mich vom Hub über die Client Connections Seite verbinden möchte,
klappt das nicht wirklich. Er verbindet sich kurz und dann bin ich auch schon wieder
disconnected mit folgender Meldung:

> CLEXI closed. Reason: 1005
> CLEXI server says welcome. Info: {"version":"CLEXI Node.js server v0.8.2","xtensions":{"clexi-broadcaster":{"active":true},"clexi-http-events":{"active":true}}}
> CLEXI connected
> CLEXI connecting ... 

Auch nach Änderung des Ports überall auf 7070 ändert sich nichts
-  ~/clexi/www/sepia/settings.js look for: "clexiSocketURI"
-  ~/clexi/settings.json look for: "port"
-  /etc/nginx/sites-enabled/sepia-client-nginx.conf
und löschen des Chromium Ordner, 2-fachem Neustart
kommt keine Besserung/Verbindung zustande.
Es bleibt beim connecten und folgendem Abbruch mit Fehler 1005.
Ich hab's im Gefühl, das kann nichts großes sein. Ich komm nur nicht drauf
bzw. was mache ich falsch/vergesse ich?

Es sind 2 Raspi's
Der Hub läuft auf 192.168.0.10 und der Client auf 192.168.0.20
![grafik](https://user-images.githubusercontent.com/64219122/81328791-c9e95a00-909d-11ea-8b89-cc9ec1955233.png)

Ach ja,...

Hier das Clexi log.out  (sieht eigentlich gut aus)
> Server with ID 'clexi-123' running at: http://127.0.0.1:7070
> Hostname: localhost - SSL: false
> CLEXI Xtensions loaded: 2

**Comment by fquirin** [comment]
Ich vermute du hast das gleiche Problem, das hier beschrieben wurde: https://github.com/SEPIA-Framework/sepia-docs/issues/32

> Schau mal bitte in deinem clexi Ordner in die settings.json.
Dort gibt es die Zeile: "idIsPassword": false,
>
>Bei dir steht wahrscheinlich true drin. Ändere das in false, starte den Clexi nochmal neu und dann sollte es das gewesen sein.

Ich war zu forsch, als ich CLEXI auf v0.8.2 upgedated habe, denn die SEPIA v2.4.X kann mit dem geänderten "Passwort" Handling noch nicht umgehen und schließt dann von selber die Verbindung sofort wieder.

**Comment by hartm11** [comment]
ja, klasse. Genau das war es.
Hab den grünen Punkt :-)
Dankeschön
