### ISSUE TITLE
TTS-Error vom Client

### ISSUE THREAD

**Issue by hartm11** [SEPIA-Framework/sepia-docs#39]
Hi zusammen,
mittlerweile bin ich schon ziemlich weit, komme aber aktuell nicht weiter.
Nach einem Neustart höre ich "Hello friend ...." und dann noch "Readdy for setup".
Ich kann den Client auch mit "Hey Sepia" aufwecken, aber selbst bei einem einfachen
Wort wie "Hallo" kommt keine Antwort. In den Sepia client connections erscheint:

Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-speech":**_{"type":"tts_error","msg":"unknown"}}}_**
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"idle"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-speech":{"type":"tts_speak","msg":"hello"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-speech":{"type":"asr_result","msg":"hello"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"idle"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"listening"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}

Zudem scheint der Client zu versuchen den gesprochenen Text als englisch zu interpretieren. Zumindest sieht es phonetisch so aus. Bei einem Satz wie:
"Wohnzimmer Licht an"      macht der Sepia Client daraus:

Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-speech":{"type":"tts_speak","msg":**_"won't see my list and_**"}}}
Aus "Wohnzimmer" wird "won't see my" / aus "Licht" wird "list" / und aus "an" wird "and"
Und folgend natürlich der tts-error (s.o.)

Achja, ...
bei "What time is it" ist im output auch "what time is it", leider aber auch der tts-error.

Hat jemand eine Idee? Vllt kann ich ja irgendwo die Sprache auf "deutsch" festtackern :-) und der tts-error verschwindet dann auch (unwahrscheinlich, aber wie das so ist mit der Hoffnung ;-).

**Comment by fquirin** [comment]
Hi,

Ein paar Fragen.
* Welche Plattform ist das? Ich vermute Raspberry Pi 3 oder 4?
* Hast du bei der Server Installation auch den Punkt 7 "Install TTS engine and voices" ausgeführt?
* Hast du irgendwas an der `settings.js` geändert? Falls ja kannst du noch mal prüfen ob `"speech-voice-engine": "sepia"` eingetragen ist?
* Nutzt du zusätzlich den SEPIA STT Server? (Docker Container)

> Ich kann den Client auch mit "Hey Sepia" aufwecken, aber selbst bei einem einfachen
Wort wie "Hallo" kommt keine Antwort

Wie ich in deinem Log sehe ist das schon der Client  v0.22.0, der ist eigentlich noch gar nicht offiziell raus, dummerweise klont das Install-Skript aber noch aus dem Dev Branch :see_no_evil: (statt dem Master). Theoretisch ist der Client kompatibel aber gerade bei TTS hat sich Einiges geändert.
Eventuell bringt ein Client downgrade etwas. Dazu könntest du einfach auf deinem Client den Inhalt des Ordners `~/clexi/www/sepia` durch die Daten aus der noch aktuellen Release Version ersetzen, Odner: `SEPIA/sepia-assist-server/Xtensions/WebContent/app`. Sorry dafür!

> Zudem scheint der Client zu versuchen den gesprochenen Text als englisch zu interpretieren.

Hier gibt es zwei Möglichkeiten. SEPIA müsste den Befehl "speak German" verstehen. Alternativ kannst du dich mit dem selben Account im Browser anmelden und in den Settings die User Sprache auf Deutsch stellen.

**Comment by hartm11** [comment]
Hi,

 

- Plattformen sind: der Client ein Raspi 2 und der Server ein Raspi 3

- Nein, hatte ich nicht installiert :-( 

  Ich dachte auch das die tts-engine auf dem Client liegt und ich sie auf dem Server nicht brauche.

- "speech-voice-engine": "sepia" ist es bei mit auch

- Nichts zusätzliches bei mir. Ich beginne immer so "flach" wie möglich um ein System zum laufen zu bekommen.

  Sonst kann man sich 2-3 Fehler zur gleichen Zeit an verschiedenen Stellen einfangen und sucht sich dann zu Tode.

 

Habe die tts-engine nachinstalliert und es geht. SUPER!!!  :-)

 

Da habe ich gleich noch eine grundsätzliche Frage dazu.

Die Sepia App habe ich auf zwei Handys ausprobiert und den Client eben auf dem Raspi 2 installiert.

Die Sprachausgabe auf den Handys ist um Faktor 10 besser als auf dem Client.

- Kann man nicht die Sprachausgabe von den Handys auch auf den Client portieren?

- Und dann habe ich noch gesehen, dass die Handys (Sepia App) keinen Clexi braucht. Wie läuft da der Datenverkehr ab?

 

So... genug Fragen für Heute ;-)

 

Viele Grüße
Jörg

 
 

Gesendet: Dienstag, 12. Mai 2020 um 19:23 Uhr
Von: "Florian Quirin" <notifications@github.com>
An: "SEPIA-Framework/sepia-docs" <sepia-docs@noreply.github.com>
Cc: "hartm11" <hartm11@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [SEPIA-Framework/sepia-docs] TTS-Error vom Client (#39)


 

Hi,

Ein paar Fragen.


	Welche Plattform ist das? Ich vermute Raspberry Pi 3 oder 4?
	Hast du bei der Server Installation auch den Punkt 7 "Install TTS engine and voices" ausgeführt?
	Hast du irgendwas an der settings.js geändert? Falls ja kannst du noch mal prüfen ob "speech-voice-engine": "sepia" eingetragen ist?
	Nutzt du zusätzlich den SEPIA STT Server? (Docker Container)



Ich kann den Client auch mit "Hey Sepia" aufwecken, aber selbst bei einem einfachen
Wort wie "Hallo" kommt keine Antwort


Wie ich in deinem Log sehe ist das schon der Client v0.22.0, der ist eigentlich noch gar nicht offiziell raus, dummerweise klont das Install-Skript aber noch aus dem Dev Branch 🙈 (statt dem Master). Theoretisch ist der Client kompatibel aber gerade bei TTS hat sich Einiges geändert.
Eventuell bringt ein Client downgrade etwas. Dazu könntest du einfach auf deinem Client den Inhalt des Ordners ~/clexi/www/sepia durch die Daten aus der noch aktuellen Release Version ersetzen, Odner: SEPIA/sepia-assist-server/Xtensions/WebContent/app. Sorry dafür!


Zudem scheint der Client zu versuchen den gesprochenen Text als englisch zu interpretieren.


Hier gibt es zwei Möglichkeiten. SEPIA müsste den Befehl "speak German" verstehen. Alternativ kannst du dich mit dem selben Account im Browser anmelden und in den Settings die User Sprache auf Deutsch stellen.

**Comment by fquirin** [comment]
> Habe die tts-engine nachinstalliert und es geht. SUPER!!!  :-)

Nice :sunglasses: 
Es kann durchaus sein, dass die Hinweise darauf noch hier und da fehlen :-/

> Die Sprachausgabe auf den Handys ist um Faktor 10 besser als auf dem Client.
- Kann man nicht die Sprachausgabe von den Handys auch auf den Client portieren?

Leider nicht, das ist ein Plattform Feature :-(
Für die neue Version v2.5.0 von SEPIA habe ich 2 weitere TTS engines integriert (pico und MaryTTS), damit dürfte das Handy dann nur noch um Faktor 3-5 besser sein ^^. Meine Hoffnungen liegen auf [MozillaTTS](https://github.com/mozilla/TTS), was mir allerdings noch etwas zu experimentell und resourcenhungrig ist und dem nächsten Update von [MaryTTS](https://github.com/marytts/marytts) (da habe ich kürzlich sogar einen pull request gemacht um die deutsche Stimme etwas zu verbessern zu können :-) ).

> - Und dann habe ich noch gesehen, dass die Handys (Sepia App) keinen Clexi braucht. Wie läuft da der Datenverkehr ab?

CLEXI ist nur nötig für das Remote-Terminal und der Verbindung zwischen RPi und SEPIA. Die generelle Kommunikation läuft über den SEPIA Chat-Server (aka WebSocket Server) oder direkte HTTP request an den SEPIA Assist- und Teach-Server.

**Comment by fquirin** [comment]
Die neuen TTS Stimmen sind jetzt im v2.5.0 Release verfügbar :-)
