### ISSUE TITLE
Wake Word Android ändern

### ISSUE THREAD

**Issue by L-S-2020** [SEPIA-Framework/sepia-docs#52]
Liebes S.E.P.I.A-Team,
zuerst mal vielen Dank für diesen wunderbaren Assistenten.
Ich wollte Fragen ob es möglich ist das Wake-Word des Android-Clienten zu ändern?

**Comment by fquirin** [comment]
Hallo und herzlich willkommen :-)
Offiziell geht das nicht, ... inoffiziell habe ich eine kleiner Hintertür für Entwickler eingebaut :sweat_smile: .
Wenn du in den Einstellungen die "Hey SEPIA" Settings öffnest, dann das Label "Debug Info" suchst und dort einen Long-Press drauf machst sollte sich ein kleines Menü öffnen. Dort kannst du die Engine Version wählen und eins der mitgelieferten WWs, z.B.: "1.6" und "bumblebee" :wink: 
Kurze Info dazu: Engine v1.4 ist in der App enthalten, v1.5 und v1.6 werden online nachgeladen (~1.5MB). Es könnte also etwas dauern bis es sich aktiviert.

**Comment by L-S-2020** [comment]
Vielen Dank

Florian Quirin <notifications@github.com> schrieb am Mo., 22. Juni 2020,
22:06:

**Comment by fquirin** [comment]
Hier ist die aktuelle Liste 

#### v1.4

hey sepia
navy blue
ok lamp
orange
purple
white
yellow

#### v1.5

alexa
americano
avocado
blueberry
bumblebee
caterpillar
christina
dragonfly
flamingo
francesca
grapefruit
grasshopper
iguana
picovoice
pineapple
porcupine
raspberry
terminator
vancouver

#### v1.6

americano
blueberry
bumblebee
crimson
deep pink
deep sky blue
dim gray
fire brick
forest green
grapefruit
grasshopper
hey edison
hey pico
hot pink
lavender blush
lime green
magenta
midnight blue
papaya whip
peach puff
picovoice
porcupine
sandy brown
terminator
white smoke
