### ISSUE TITLE
Deeplinks Android

### ISSUE THREAD

**Issue by L-S-2020** [SEPIA-Framework/sepia-docs#54]
Liebes S.E.P.I.A-Team,
ist möglich Deeplinks (um eine App via URL zu öffnen) in einem externen Browser zu öffnen, da ich im In-App Browser immer die Fehlermeldungen:
net::ERR_UNKNOWN_URL_SCHEME
oder
net::ERR_FILE_NOT_FOUND
bekomme.

**Comment by fquirin** [comment]
Hi,

das bezieht sich auf die Android App oder?
Es ist möglich und sollte eigentlich auch passieren (wie z.B. bei Google Maps), falls die URL erkannt wird oder nicht explizit mit "http" bzw. "https" anfängt.
Welche URL macht Probleme?

Grüße,
Florian

**Comment by L-S-2020** [comment]
Eigentlich alle, (außer Google Maps) die mit einer App vernetzt sind. Bei Firefox funktionieren die Weiterleitungen (zu den Apps) einwandfrei. Ich schicke mal ein Screenshot von music amazon.de (der Link sollte eigentlich die Amazon Music App öffnen):
![Screenshot_20200627_183158_de bytemind sepia app web](https://user-images.githubusercontent.com/67273491/85927209-e4bd9b00-b8a4-11ea-8f0a-37291999069a.jpg)

**Comment by fquirin** [comment]
So wie es aussieht sucht er im App root nach "music.amazon.de" weil das Protokoll im Link fehlt. Hast du selber die Kontrolle über die URL? Falls ja setze mal ein "https://" davor 😉. Falls er dann die Website öffnet sollte angeblich auch "amznmp3://" als Schema gehen.

**Comment by L-S-2020** [comment]
Vielen Dank, jetzt funktioniert es.

Florian Quirin <notifications@github.com> schrieb am Sa., 27. Juni 2020,
19:07:
