### ISSUE TITLE
Manuelle .items files in openHAB können nicht bearbeitet werden

### ISSUE THREAD

**Issue by Smarthome-Creator** [SEPIA-Framework/sepia-docs#65]
Hallo,

es gibt leider noch ein brachial nerviges Problem mit Sepia und openHAB 2. Wenn man in openHAB Items manuell anlegt, können diese nicht von Sepia "getagt" werden.
Das Problem ist leider ein grundlegendes in openHAB selbst, warum auch immer konnte ich bis heute nicht herausfinden. Files die man manuell erstellt können z.B. nicht über die Paper UI weiter bearbeitet werden. Erstellt man über die Paper UI neue Items, werden diese mit über die REST API "getagt", nicht so aber manuell erstellte.

Lange Rede kurzer Sinn, hast du irgendeinen Tipp oder eine Ahnung wie dieses Problem zu lösen ist? Du kannst die manuellen Items leider nicht im Sepia HUB bearbeiten, weil Sepia die Tags nicht setzen kann.

Ich habe es mal mit einem Item zufällig irgendwie hingekriegt dieses über Sepia zu bearbeiten, das aber nur weil ich auf der Datei tausendmal irgendwelche Berechtigungen geändert habe und absolut nicht mehr weiß wie ich das am Ende hinbekommen habe.

Danke und Gruß

**Comment by sepia-assistant** [comment]
Hi,

wie du schon sagst kann scheinbar selbst openHAB die .item files nicht bearbeiten, deswegen scheitert auch SEPIA daran. SEPIA schickt Infos an openHAB über die REST API, ab diesem Punkt kann nur openHAB die Daten in die Datei schreiben.

Es gibt noch eine andere Möglichkeit, die eventuell aber andere Nachteile bringt in deinem Setup. Über den sog. ["Internal HUB"](https://github.com/SEPIA-Framework/sepia-docs/wiki/Smart-Home-Controls#tutorial-sepia-internal-multi-hub) von SEPIA kannst du auch openHAB items einbinden und diese völlig unabhängig von openHAB konfigurieren. Das ganze wird dann in SEPIAs Datenbank gespeichert und zeigt lediglich auf die Geräte URL in openHAB. Der Nachteil ist, dass Geräte von openHAB nicht mehr automatisch ausgelesen werden und du alles was du in SEPIA nutzen willst per Hand hinzufügen musst. Bei 5 Geräten geht das, bei 50 ist es wohl eher nervig :see_no_evil:

**Comment by Smarthome-Creator** [comment]
Hi,

ich hatte gedacht das man die Sepia Tags auch manuell in die Files schreiben kann aber ich habe im openHAB Forum erfahren das es in OH 3 um einiges leichter wird manuell erstellte Files in die JSON DB zu migrieren.

Frage ist beantwortet ich mach das hier zu.

Danke dir.
