### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mick69** [SEPIA-Framework/sepia-docs#67]
I have Linux Mint laptop and windows 10 laptop connected to mobile phone hotspot, ip address 192.168.43.54 and 192.168.43.45, have disabled firewall on both,  Linux has the sepia server and self signed certificate for nginx,  http works but https comes up 192.168.43.54 refused to connect.

**Comment by fquirin** [comment]
Hi Mick,
when you use self-signed Certificates you usually need to import them on each device that wants to connect because the browser will not accept them without a warning. What client do you use? (Browser, Android App, Headless?)

**Comment by mick69** [comment]
Hi Florian, Opera on windows 10,  detected the certificate but warned not certified,  also can’t get the firewall settings in Linux ufw to work, https://192.168.43.54:20726/sepia http://192.168.43.54:20721/app/index.html worked ok with ufw incoming set to allow thanksMichael Sent from Mail for Windows 10 From: Florian QuirinSent: Thursday, 3 September 2020 5:55 PMTo: SEPIA-Framework/sepia-docsCc: mick69; AuthorSubject: Re: [SEPIA-Framework/sepia-docs] help (#67) Hi Mick,when you use self-signed Certificates you usually need to import them on each device that wants to connect because the browser will not accept them without a warning. What client do you use? (Browser, Android App, Headless?)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fquirin** [comment]
Hi Mick,
I have no experience with Opera and how it reacts to self-signed certificates.
Do you have Chrome, Firefox or the new Edge installed on your system as well?

**Comment by mick69** [comment]
yes, have chrome and edge

**Comment by mick69** [comment]
Hi Florian Same error with chrome and edge on https - 192.168.43.54 refused to connect. Also, http works but rejects username and password, how do you fix on the server? Do you have windows and linux ufw firewall rules? ThanksMichael Sent from Mail for Windows 10 From: Michael RossSent: Friday, 4 September 2020 8:38 AMTo: reply@reply.github.comSubject: Re: [SEPIA-Framework/sepia-docs] help (#67) yes, have chrome and edge On Thu, 2020-09-03 at 13:57 +0000, Florian Quirin wrote:> Hi Mick,> I have no experience with Opera and how it reacts to self-signed> certificates.> Do you have Chrome, Firefox or the new Edge installed on your system> as well?> —> You are receiving this because you authored the thread.> Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by fquirin** [comment]
Hi Mick,

If you use Chrome you should see a warning message saying the page is not safe. If you see that you can follow these steps to add your self-signed certificate: [>link<](https://www.ge.com/digital/documentation/historian/version80/t_hgs_enabling_trust_for_a_self_signed_certificate.html).
Before you add the certificate you can also try to use the "details" button and then select to open the page anyway.

> Do you have windows and linux ufw firewall rules?

I've been using Windows 8 and 10, Debian/Raspbian 9 and 10 and Ubuntu 18 and in no system I had to configure any specific firewall rules.
Since it seems to work for you in HTTP mode I don't think that any firewall is blocking access. The firewall would block the whole port for both HTTP and HTTPS.
What system do you use? Are there any specific security settings?

**Comment by mick69** [comment]
Hi Florian Originally in Opera,  I got a warning message saying the page is not safe, and overrid. The Linux ubuntu/mint ufw default setting is deny incoming and allow outgoing,  have to change incoming to allow to get login prompt on http,  googled/duckduckgod how to set rules for ufw but doesn’t work. How do I login with the password set during install and reset on the server if required, I get login or server error. ThanksMichael  Sent from Mail for Windows 10 From: Florian QuirinSent: Friday, 4 September 2020 7:07 PMTo: SEPIA-Framework/sepia-docsCc: mick69; AuthorSubject: Re: [SEPIA-Framework/sepia-docs] help (#67) Hi Mick,If you use Chrome you should see a warning message saying the page is not safe. If you see that you can follow these steps to add your self-signed certificate: >link<.Before you add the certificate you can also try to use the "details" button and then select to open the page anyway.Do you have windows and linux ufw firewall rules?I've been using Windows 8 and 10, Debian/Raspbian 9 and 10 and Ubuntu 18 and in no system I had to configure any specific firewall rules.Since it seems to work for you in HTTP mode I don't think that any firewall is blocking access. The firewall would block the whole port for both HTTP and HTTPS.What system do you use? Are there any specific security settings?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mick69** [comment]
Hi Florian Got the firewall rule to work and got the http login to work once and talk to and configure sepia,  I think my problem is only having 1.5gb ram on my linux laptop, shall try installing server on my 8gb windows 10 laptop. ThanksMichael Sent from Mail for Windows 10 From: Florian QuirinSent: Friday, 4 September 2020 7:07 PMTo: SEPIA-Framework/sepia-docsCc: mick69; AuthorSubject: Re: [SEPIA-Framework/sepia-docs] help (#67) Hi Mick,If you use Chrome you should see a warning message saying the page is not safe. If you see that you can follow these steps to add your self-signed certificate: >link<.Before you add the certificate you can also try to use the "details" button and then select to open the page anyway.Do you have windows and linux ufw firewall rules?I've been using Windows 8 and 10, Debian/Raspbian 9 and 10 and Ubuntu 18 and in no system I had to configure any specific firewall rules.Since it seems to work for you in HTTP mode I don't think that any firewall is blocking access. The firewall would block the whole port for both HTTP and HTTPS.What system do you use? Are there any specific security settings?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mick69** [comment]
Problem appears to be ram on Linux laptop,  only 1.5gb
