### ISSUE TITLE
Multi language support.

### ISSUE THREAD

**Issue by MrTheBarbarian** [SEPIA-Framework/sepia-docs#77]
Hi! The project looks very well! I'm surching something like this since a long time. I like the concept, but I didn't install it and didn't tested it yet. I saw that the assistant understand two languages onley. I desid to not west my time for testing before asking what is the future manner for translations in other languages.
I would like to know do you have written procedures for translation? I'm interested to help. 
There is many assistant, but all of them work with few languages, but don't understand Bulgarian. 
I can help to add bulgarian language to your project, if you are interested. 
Also it will very nice if you deside to use platform like https://crowdin.com/.
Thanks!

**Comment by fquirin** [comment]
I've build everything from the beginning with support for English and German to make sure other languages can be added later in a well defined way. Unfortunately translating the natural language processing is not trivial and for things like the speech recognition and text-to-speech engines there is sometimes simply no open-source data available.
I should probably write an article about it at some point in time to at least explain the basics required to translate SEPIA, but right now priority is to improve the existing languages, sorry.

**Comment by MrTheBarbarian** [comment]
Hello! I am very interested of this project. I'm not a programmer, but I have knowledge of programming. If you need help for testing or some easy jobs, I am ready to help.

**Comment by fquirin** [comment]
There is some very basic (experimental) support for Russian in the SEPIA client and server. Would this be interesting for you as well?  

I'll try to put some features in the next version to make integration of new languages easier or at least to make them available for experiments :-)

**Comment by MrTheBarbarian** [comment]
Thanks! It will very useful! 
So, if I make a fork, and translate all strings from English and German to Bulgarian in separate files, can I ask for pull request? Is will be ok for the beginning?

**Comment by fquirin** [comment]
There will be a few bugs I expect but it would be a very good start :-)
