### ISSUE TITLE
openHAB connection not working

### ISSUE THREAD

**Issue by MtotheKay** [SEPIA-Framework/sepia-docs#8]
It seems that the openHAB connection is not working properly. 

The "lights on" command returns:
> Currently I'm not connected to any smart home system

- Getting the devices via Menu -> Smart Home -> GET DEVICES works
- The user is assigned to the roles "user, smarthomeguest"
- I entered the IP for the openhab_host setting in ~/SEPIA/sepia-assist-server/Xtensions/sepiassist.custom.properties (Even though it is legacy?!)
- To be sure I did also enter it in smarthome_hub_host and put openHAB for the 
smarthome_hub_name

SEPIA Server: Raspberry PI 3 B with Raspbian 9 (stretch)

**Comment by fquirin** [comment]
Hi MtotheKay,

I'm using it daily so in theory it should work :-/
Lets check the configuration again.
* The 'legacy' setting 'openhab_host' is still working and will overwrite the URL given via 'smarthome_hub_host'
* 'smarthome_hub_name' for openHAB is hardcoded as 'openhab' (lower-case letters) ... this should not make a difference ... but I just checked the code and there might be a missing conversion to all lower-case O_o *doh*
* Something that might play a role as well is a mix of http and https addresses ... but I don't think that's the case here especially when GET DEVICES works for you

Lets try the lower-case point first ;-)

**Comment by MtotheKay** [comment]
It works.

here is what I did:
- Comment out the legacy line, so that only the smarthome_hub_* settings are active.
- Used the Servername instead of the IP Address
- Used only lower case letters for the smarthome_hub_name e.G. `smarthome_hub_name=openhab`
- Restated the Raspberry which runs S.E.P.I.A.

Not sure which step resolved the problem, but it works now. 
Thanks a lot.

**Comment by fquirin** [comment]
I'm pretty sure it was the lower-case issue, I've already fixed this internally for the next version ^^.
Server restart is necessary, thats true as well, unless you use the "server reload" button in the Control-HUB.
The server address usually only makes a difference if the server cannot access the same network and thus cannot see the IP.
