### ISSUE TITLE
Update des DIY Clients

### ISSUE THREAD

**Issue by Smarthome-Creator** [SEPIA-Framework/sepia-docs#80]
Hallo,
mal wieder vielen Dank für den neuen sehr umfangreichen Release. Kurze Frage dazu, den DIY Client hast du aber noch nicht auf die 0.23.0 geupdatet oder?

Gruß

**Comment by PlanetSmasher** [comment]
Im Changelog steht relativ weit unten
>In preparation: updated SDK, DIY client scripts and Docker containers

Ich glaube also, das wir einfach etwas Geduld brauchen ;)

**Comment by fquirin** [comment]
Hallo :-)
Der DIY Client zieht sich bei der Installation jetzt den Client aus dem neuen Master branch, sprich die Version 0.23.0.
Es gibt einige Verbesserungen bei den run-scripts etc. aber falls es damit bisher keine Probleme gab würde es theoretisch reichen ein Update der Dateien in `~/clexi/www/sepia` auszuführen (einfach die aus dem neuen Release drüber kopieren, z.B. vom Server: `\sepia-assist-server\Xtensions\WebContent\app\`).

**Comment by Smarthome-Creator** [comment]
Okay, das ist ein bisschen komisch, da ich den DIY neu installiert habe und immer noch die 0.22.0 bekommen habe. 
Was könnte ich da falsch gemacht haben?

**Comment by fquirin** [comment]
komisch, wann hast du neu installiert?

**Comment by Smarthome-Creator** [comment]
Direkt nach dem die Android App aktuallisiert wurde. Erst den Server geupdatet und dann wollte ich den DIY updaten. Da ich da aber keine Doku gefunden habe wie man den updatet habe ich ihn neu installiert, getestet und gesehen das es wieder die 0.22.0 war. Wenn du sagst es müsste aber die 0.23.0 geladen werden dann versuche ich es einfach nochmal.

**Comment by fquirin** [comment]
Habe gerade testweise noch mal frisch installiert und die 0.23.0 auf meinem Pi :-)
Übrigens teste ich gerade das Set von Waveshare mit dem RPi Audio Hat + Lautsprecher ... spontan sehr positiv überrascht :sunglasses:

**Comment by Smarthome-Creator** [comment]
Habe jetzt auch nochmal ganz frisch installiert und bekomme jetzt die 0.23.0. Allerdings stelle ich gerade fest das diese bei mir schlechter läuft als die 0.22.0. Der Client hängt sich jetzt immer im state 'idle' auf.

Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"idle"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-speech":{"type":"asr_error","msg":"Es tut mir leid, aber es gab ein unerwartetes Problem mit der Spracherkennung. Error: 'E0? - network'"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"idle"}}}

Da hilft nur manuelles antriggern: 
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"listening"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"loading"}}}
HTTP event: {"name":"remote-button","data":{"deviceId":"s1","button":"mic"}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-speech":{"type":"tts_error","msg":"unknown"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"idle"}}}
HTTP event: {"name":"remote-button","data":{"deviceId":"s1","button":"mic"}}

Aber leider entstehen auch hier Fehler. Hat sonst schon jemand Erfahrungen mit dem neuen Client?

Gruß

**Comment by fquirin** [comment]
> Error: 'E0? - network'

Das kommt eigentlich wenn die ASR engine auf 'native' steht und der Client keine Verbindung mit dem Spracherkennungsserver herstellen kann (und bei Microsoft Edge Canary als bug). Kann es sein dass dein Pi keine Verbindung zum Internet aufbauen kann?

**Comment by Smarthome-Creator** [comment]
Hallo,
manchmal sieht man halt auch den Wald vor lauter Bäumen nicht. Der DIY Client läuft jetzt wirklich wirklich gut, wenn man die Config nach einer Neuinstallation wieder richtig einstellt. ;-) Keine Abstürze mehr und auch kein hängenbleiben in irgendeinem Status.
Die Wake Word Erkennung ist zwar leider nach wie vor noch recht "schwierig" aber das passt soweit auch erstmal.

Ich kriege nur ums verrecken den MaryTTS nicht an den Start. Ich habe ihn mit deinem Script auf einem extra Raspi mit 8GB installiert, kann ihn starten aber er scheint einfach nicht erreichbar zu sein. Hattest du da schon eine Anleitung geschrieben?

Ich mach das hier zu.

Gruß

**Comment by fquirin** [comment]
@Smarthome-Creator Zu den TTS Sachen gabs bisher glaub nur die [Readme im TTS Ordner](https://github.com/SEPIA-Framework/sepia-assist-server/tree/master/Xtensions/TTS), kanntest du die schon?

**Comment by Smarthome-Creator** [comment]
Danke, hab ich mir durchgelesen, das Problem gefunden, jetzt läufts.
