### ISSUE TITLE
Automated clexi client login on startup

### ISSUE THREAD

**Issue by dirtydother** [SEPIA-Framework/sepia-docs#83]
Hello,

is there a possibility after rebooting the system that the clexi client login (call login user [user-ID] password [user-pwd]) and client reload will be done automatically?
(Sepia server and Sepia client are on the same device).

Best regards

**Comment by fquirin** [comment]
Hi @dirtydother ,
this should actually happen by default unless for some reason the client cannot store its settings permanently.
Do you use a clean DIY client installation or some custom setup?

**Comment by dirtydother** [comment]
Hi,

seems so :-(
I did the installation as described on https://github.com/SEPIA-Framework/sepia-installation-and-setup/blob/master/sepia-client-installation/rpi/README.md

Nothing special and no customizing.

**Comment by fquirin** [comment]
Ok thats odd :-/

Just to make sure, this is what's happening?
- You start the DIY client (`cd ~/sepia-client` + `bash run.sh` or auto-start after login)
- You connect with any SEPIA Control-HUB app via the 'client connections' page to your DIY client CLEXI server
- You use `call login user [user-ID] password [user-pwd]` to login the your DIY client
- Client tests are working
- You reload the DIY client (manual shutdown or reboot via message type 'Runtime Command: `osReboot`)
- You wait for the client to restart and the connection to automatically connect
- You hear "ready for setup" and the client goes back to setup-mode instead of automatically logging in

Is that correct?

**Comment by dirtydother** [comment]
Yes, it's exactly as you described it. As soon as I restart, the "ready for setup" appears. Below is the log of the SEPIA Control-HUB:

Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","event":{"state":"active","user":"setup"}}}
CLEXI server says welcome. Info: {"version":"CLEXI Node.js server v0.8.2","xtensions":{"clexi-broadcaster":{"active":true},"clexi-http-events":{"active":true},"runtime-commands":{"active":true}}}
CLEXI connected
CLEXI connecting ...
CLEXI reconnecting after unexpected close. Try: 6
[...]
CLEXI error
CLEXI connecting ...
CLEXI reconnecting after unexpected close. Try: 1
CLEXI closed. Reason: 1006
[...]
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"listening"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"inactive"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"triggered","word":"hey_edison"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"active"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","event":{"state":"active","user":"uid1007"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","msg":"Reloading client."}}
Broadcaster response: "sent"
Broadcaster event: {"broadcast":{"name":"sepia-client","data":{"deviceId":"o1","call":"reload"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"active"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"error","msg":"Cannot read property 'apply' of undefined"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-wake-word":{"state":"inactive"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","event":{"state":"active","user":"uid1007"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","sepia-login":{"note":"loginSuccess"}}}
Broadcaster event: {"broadcast":{"client":"o1_chrome_app_v0.22.0","deviceId":"o1","msg":"Logging in with new user: uid1007. Plz wait."}}

**Comment by fquirin** [comment]
Hmm :thinking: 
Did you create any other users besides "pi"? Or do you use the desktop version of Raspbian maybe?
Maybe the folder that was created for the browser `~/sepia-client/chromium` is for some reason write protected?

**Comment by dirtydother** [comment]
I did the whole installation process on a raspi 4 and now everything's working fine.
I don't know what's the problem on my raspi 3. I did the whole installation process five, six times for sure and it never worked :-D

I will close this issue. If I should ever find out what the problem has been, I will let you know.
