### ISSUE TITLE
Configuration of a custom voice engine

### ISSUE THREAD

**Issue by dirtydother** [SEPIA-Framework/sepia-docs#84]
Hello,

how do I have to change the settings.js that the pico voice engine will be used by the client?
I played a little bit with "speech-voice-engine" and "speech-asr-engine", but didn't get it working.

Best regards

**Comment by fquirin** [comment]
Hi,

if you've installed the voices during the SEPIA server installation (`bash setup.sh` -> step 7 ) there should be the an option 'native' for 'speech-asr-engine' and the voice could be for example `en-US pico f`. In the settings file it should look like this:
```
"speech-asr-engine": "native"
...
"en-voice": "en-US pico f"
```

**Comment by fquirin** [comment]
sorry I just realized that I copied the wrong entry, please use `"speech-voice-engine": "sepia"` :sweat_smile:

**Comment by dirtydother** [comment]
Hi,

it's working! (Didn't have to do the install step 7, but only insert the "en-US pico f" part).
Thank you very much!
