### ISSUE TITLE
Andere Stimme für den DIY Client

### ISSUE THREAD

**Issue by Smarthome-Creator** [SEPIA-Framework/sepia-docs#92]
Hallo,
ich muss hier leider nochmal nachfragen ob ich etwas falsch mache oder es sich vielleicht um ein Bug handelt.
Nach dem der marytts nun läuft wollte ich dem DIY eine andere Stimme verpassen und habe dazu bereits diesen Issue dazu gelesen: [https://github.com/SEPIA-Framework/sepia-docs/issues/84](url)

Leider hat das nicht funktioniert da ich nun immer einen Error vom Client bekomme:

Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-speech":{"type":"tts_error","msg":"unknown"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"idle"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-state":{"state":"loading"}}}
Broadcaster event: {"broadcast":{"client":"s1_chrome_app_v0.23.0","deviceId":"s1","sepia-speech":{"type":"tts_speak","msg":"Ja, es funktioniert!"}}}

Kann mir vielleicht jemand sagen ob ich was falsch mache?

Hier noch meine settings.js:

`device: {
                        "host-name": "192.168.0.55",
                        "deviceId": "s1",
                        "deviceLocalSiteData": {
                                "location": "home",
                                "type": "room",
                                "name": "unassigned",
                                "index": ""
                        },
                        "en-voice": "",
                        "de-voice": "",
                        "wakeWordSensitivity": [1.0]
                },
                user: {
                        "clexiSocketURI": "ws://localhost:8080",
                        "clexiServerId": "clexi-123",
                        "clexiConnect": true,
                        "useRemoteCmdl": true,
                        "speech-voice-engine": "de-DE marytts f",
                        "speech-asr-engine": "native",
                        "speech-websocket-uri": "ws://localhost:20741/stt/socket",
                        "useGamepads": true,
                        "useBluetoothBeacons": true,
                        "useBluetoothBeaconsInAoModeOnly": false,
                        "useWakeWord": true,
                        "autoloadWakeWord": true,
                        "allowWakeWordDuringStream": true,
                        "activeSkin": "2",
                        "activeAvatar": "0",
                        "proactiveNotes": false,
                        "autoGPS": false
                },

Danke`

**Comment by neporamone** [comment]
hi 
Müßte der Eintrag bei `speech-voice-engine`   **"de-DE marytts f"** nicht bei `de-voice` stehen ?!
Was dann unter "speech-voice-engine" stehen muß, bin ich überfragt.

Tschau nepo

**Comment by Smarthome-Creator** [comment]
> 
> 
> hi
> Müßte der Eintrag bei `speech-voice-engine` **"de-DE marytts f"** nicht bei `de-voice` stehen ?!
> Was dann unter "speech-voice-engine" stehen muß, bin ich überfragt.
> 
> Tschau nepo

Die Idee hatte ich auch schon und es auch versucht aber das endete mit dem gleichen Ergebnis.

Meine Vermutung ist eher das man bei "speech-voice-engine" eher sowas wie "marytts" und bei "de-voice" dann "de-DE marytts f" eintragen muss. Das muss ich aber noch testen.

**Comment by fquirin** [comment]
`"speech-voice-engine": "sepia"` (Default Einstellung) und `"de-voice": "de-DE marytts f"` müsste funktionieren

**Comment by Smarthome-Creator** [comment]
> 
> 
> `"speech-voice-engine": "sepia"` (Default Einstellung) und `"de-voice": "de-DE marytts f"` müsste funktionieren

Das funktioniert ganz wunderbar, ich danke dir und schließe das Ticket.

Gruß

**Comment by cap-blackbeard** [comment]
Nach der Neuinstallation des DIY-Clients kann der Client die "de-DE marrytts m" Stimme nicht mehr benutzen. 
Der Chat zeigt: UI: TTS Fehler - Ausgabe konnte nicht generiert werden.
Es funktioniert nur noch die "automatic".

**Comment by cap-blackbeard** [comment]
Vielleich kann ich noch erklären, dass der MarryTTS-Server beim Containerstart scheinbar erfolgreich gestartet wird:
```Starting MaryTTS server, please wait ...
INFO: This extension is recommended for systems with 2GB memory or more.
....MaryTTS server looks GOOD.```

**Comment by fquirin** [comment]
In der Tat, konnte den Fehler reproduzieren :grimacing: 
Da ist ein Bug in der neuen Config Datei: `~/SEPIA/sepia-assist-server/Xtensions/TTS/settings.json`, die `LOCALE` Variable für die deutschen Stimmen muss `"de"` sein, nicht `"de_DE"` wie bei den englischen Stimmen :-/. KA wie ich das übersehen konnte beim Testen :-(.
Kannst du die Datei mal ersetzen durch diese hier:
[settings.zip](https://github.com/SEPIA-Framework/sepia-docs/files/8074167/settings.zip)
