### ISSUE TITLE
Teach trigger multiple devices

### ISSUE THREAD

**Issue by gu3nter** [SEPIA-Framework/sepia-docs#97]
Hallo,

Zu aller erst, vielen vielen Dank für das Tolle Tool.

ich hätte eine Frage:
Ist es möglich mit der "teach" Funktion z. B. "Alle Lampen an" mehrere Lampen zu aktivieren?

Ich habe es wie folgt versucht:
When I say:
Alle Lichter an

the assistant does ...
Control smart home device

Smart device (Light, Heater, ...)
`<light>;;Stehlampe;<light>;;Fernsehbeleuchtung`

Room (living room, kitchen, ...)
`<livingroom>`

Action (on, off, set ...):
`<on>`

Wenn ich nun den Befehl:
"Alle Lampen an", wird nur Fernsehbeleuchtung angeschaltet.

Mach ich etwas falsch?

Ich hoffe ihr könnt mir helfen.

Gruß

René

**Comment by fquirin** [comment]
Hi,

> `<light>;;Stehlampe;<light>;;Fernsehbeleuchtung`

Der Syntax ist so leider nicht möglich und momentan ist es so, dass immer nur ein Gerät getriggert werden kann. Falls das Ziel unklar ist wird der User gefragt bis das Gerät eindeutig ist.
Ich habe schon länger auf der To-Do Liste stehen, das zwischen Singular und Plural unterschieden werden sollte ^^.
Was aber normalerweise möglich ist, ist im Smart Home HUB selbst eine pseudo-Gerät zu definieren, was mehrere andere Geräte toggled.
Welchen HUB benutzt du?

**Comment by fquirin** [comment]
Mit Sicherheit, leider kenne ich mich da nicht so gut aus. Guck mal ob das hier vielleicht hilft: https://forum.iobroker.net/topic/538/mehrere-objekte-schalten/4

**Comment by gu3nter** [comment]
Ok super danke, werde mich mal einlesen
