### ISSUE TITLE
mqtt sendet  {"state":"on"}

### ISSUE THREAD

**Issue by hajobu** [SEPIA-Framework/sepia-docs#98]
Hallo
ich habe nachdem ich von Snips ins Bockshorn gejagt wurde mich wieder an eine Sprachsteuerung getraut. Installation, Einrichten klappte mit viel Suchen und Probieren. Jetzt stehe ich auf dem Schlauch. 
Ich habe unter Smart Home - internal (Sepia) meinen mosquitto server eingetragen.
Ein device eingerichtet, Interface Editor MQTT Publisher eingerichtet.
Das device sendet auch
Beispiel: sepia/smart-devices/wohnen/licht/decke/schalten {"state":"on"}
Damit schaltet das device nur aus, egal ob on,1, off oder 0 hinter  {"state":" steht.
Das "state:" muss weg. Wie bekomme ich das hin?

**Comment by fquirin** [comment]
Hi hajobu,

wie werden die Daten den später weiterverarbeitet ab dem Punkt, wo sie beim MQTT ankommen? Sprich welches System lauscht auf dem MQTT Topic und reagiert darauf?
SEPIA hat ein fixes Output Format und soweit ich das sehe kommt genau das am MQTT an, was ankommen soll. Bei einem System wie Node-RED z.B. könntest du jetzt das Objekt {"state":"on"} mit einer Node in das Format konvertieren, dass dein Gerät braucht.

> Einrichten klappte mit viel Suchen und Probieren

Aus eigenem Interesse, woran hat es da gehakt? Vielleicht kann ich ja die Dokumentation entsprechend erweitern.

**Comment by hajobu** [comment]
An mosquitto schließt sich smarthomeng mit dem mqtt plugin aus dem knx-user-forum an. Ich habe mehrere cilents die Daten über mosquitto an smarthomeng senden. 
Da wären
eine zweite Instanz im Keller über den die komplette Heizungsanlage, ein Wechselrichter und der Stromzähler läuft
ein wlanthermo aus dem Grillsportverein
snips bzw was davon übrig ist
ich habe in win10 den mqtt explorer installiert, der zeigt das sepia "{"state":"on"}" sendet. Die anderen senden " true" oder "1".
Ich dachte schon das das für den node red ausgelegt ist, wollte den eigentlich umgehen, bei sinps hatte das mit einem python script funktioniert.
Empfangen klappt übrigens auch nicht. Ich denke da braucht sepia auch die Klammer state Antwort.
Über die custom config habe ich auch schon einiges probiert- ohne Erfolg.

**Comment by fquirin** [comment]
Den grundsätzlichen Output für MQTT könnte man nur verändern durch einen custom service, aber das passt hier eher nicht. 
SmartHomeNG ist mir noch völlig neu, sieht aber ganz interessant aus. Scheinbar gibt es da die Möglichkeit Python Skripte einzubinden. Das könnte man bestimmt nutzen um das JSON aus dem einen Kanal in einen einfachen Text für einen andern Kanal umzuwandeln :thinking:

**Comment by hajobu** [comment]
es kommt nicht in smarthomeng an sondern bleibt in mosquitto stecken
mosquitto macht sowohl aus {"state":"on"} als auch aus {"state":"off"} ein "false"
Ich habe node red installiert und arbeite mich dort ein, hatte ich immer schon vor, man stolpert überall darüber
